package org.codetab.uknit.itest.operator;

public class RelationalNoSplitTest {
    @InjectMocks
    private RelationalNoSplit relationalNoSplit;

    @BeforeEach
    public void setUp() throws Exception {
        MockitoAnnotations.openMocks(this);
    }

    @Test
    public void testCheckRelational() {

        boolean actual = relationalNoSplit.checkRelational();

        assertTrue(actual);
    }

    @Test
    public void testCheckConditional() {

        boolean actual = relationalNoSplit.checkConditional();

        assertTrue(actual);
    }
}
