package org.codetab.uknit.itest.nested.local;

import org.codetab.uknit.itest.nested.local.Model.Logger;
class LocalTest {
    @InjectMocks
    private Local local;

    @BeforeEach
    public void setUp() throws Exception {
        MockitoAnnotations.openMocks(this);
    }

    @Test
    public void testValidatePhoneNumberIfCurrentNumberLength() {
        String phoneNumber1 = "Foo";
        String phoneNumber2 = "Bar";
        Local.validatePhoneNumber(phoneNumber1, phoneNumber2);

        fail("unable to assert, STEPIN");
    }

    @Test
    public void testValidatePhoneNumberElseCurrentNumberLength() {
        String phoneNumber1 = "Foo";
        String phoneNumber2 = "Bar";
        Local.validatePhoneNumber(phoneNumber1, phoneNumber2);

        fail("unable to assert, STEPIN");
    }

    @Test
    public void testValidatePhoneNumber() {
        String phoneNumber1 = "Foo";
        String phoneNumber2 = "Bar";
        Local.validatePhoneNumber(phoneNumber1, phoneNumber2);

        fail("unable to assert, STEPIN");
    }

    @Test
    public void testValidatePhoneNumberStringString() {
        String phoneNumber1 = "Foo";
        String phoneNumber2 = "Bar";
        Local.validatePhoneNumber(phoneNumber1, phoneNumber2);

        fail("unable to assert, STEPIN");
    }
}
