package org.codetab.uknit.itest.array;

public class CreatePrimitiveTest {
    @InjectMocks
    private CreatePrimitive createPrimitive;

    @BeforeEach
    public void setUp() throws Exception {
        MockitoAnnotations.openMocks(this);
    }

    @Test
    public void testCreateIntArray() {
        int[] anArray = new int[2];

        int[] actual = createPrimitive.createIntArray();

        assertArrayEquals(anArray, actual);
    }

    @Test
    public void testCreateIntTwoDimArray() {
        int[][] anArray = new int[2][3];

        int[][] actual = createPrimitive.createIntTwoDimArray();

        assertArrayEquals(anArray, actual);
    }

    @Test
    public void testDeclareAndCreateIntArray() {
        int[] anArray = new int[2];

        int[] actual = createPrimitive.declareAndCreateIntArray();

        assertArrayEquals(anArray, actual);
    }

    @Test
    public void testDeclareAndCreateIntTwoDimArray() {
        int[][] anArray = new int[2][4];

        int[][] actual = createPrimitive.declareAndCreateIntTwoDimArray();

        assertArrayEquals(anArray, actual);
    }

    @Test
    public void testCreateAndAcessIntArray() {
        int[] anArray = new int[2];

        int[] actual = createPrimitive.createAndAcessIntArray();

        assertArrayEquals(anArray, actual);
    }
}
