package org.codetab.uknit.itest.array;

public class CreateStringTest {
    @InjectMocks
    private CreateString createString;

    @BeforeEach
    public void setUp() throws Exception {
        MockitoAnnotations.openMocks(this);
    }

    @Test
    public void testCreateStringArray() {
        String[] anArray = new String[1];

        String[] actual = createString.createStringArray();

        assertArrayEquals(anArray, actual);
    }

    @Test
    public void testDeclareAndCreateStringArray() {
        String[] anArray = new String[1];

        String[] actual = createString.declareAndCreateStringArray();

        assertArrayEquals(anArray, actual);
    }

    @Test
    public void testCreateAndAcessStringArray() {
        String[] anArray = new String[1];

        String[] actual = createString.createAndAcessStringArray();

        assertArrayEquals(anArray, actual);
    }
}
