package org.codetab.uknit.itest.nest;

public class AnonymousClassAbstractTest {
    @InjectMocks
    private AnonymousClassAbstract anonymousClassAbstract;

    @BeforeEach
    public void setUp() throws Exception {
        MockitoAnnotations.openMocks(this);
    }

    @Test
    public void testAdd() {
        Calc calc = Mockito.mock(Calc.class);
        anonymousClassAbstract.add(calc);

        ArgumentCaptor<Addable<Integer>> captorA = ArgumentCaptor.forClass(Addable.class);

        verify(calc).op(1, 2, captorA.capture());
    }
}
