package org.codetab.uknit.itest.nest;

public class HelloWorldAnonymousClassNoSplitTest {
    @InjectMocks
    private HelloWorldAnonymousClassNoSplit helloWorldAnonymousClassNoSplit;

    @BeforeEach
    public void setUp() throws Exception {
        MockitoAnnotations.openMocks(this);
    }

    @Test
    public void testSayHello() {
        helloWorldAnonymousClassNoSplit.sayHello();
        fail("unable to assert, STEPIN");
    }
}
