package org.codetab.uknit.itest.nest;

public class LocalClassTest {
    @InjectMocks
    private LocalClass localClass;

    @BeforeEach
    public void setUp() throws Exception {
        MockitoAnnotations.openMocks(this);
    }

    @Test
    public void testValidatePhoneNumberIf() {
        String phoneNumber1 = "Foo";
        String phoneNumber2 = "Bar";
        LocalClass.validatePhoneNumber(phoneNumber1, phoneNumber2);
        fail("unable to assert, STEPIN");
    }

    @Test
    public void testValidatePhoneNumberElse() {
        String phoneNumber1 = "Foo";
        String phoneNumber2 = "Bar";
        LocalClass.validatePhoneNumber(phoneNumber1, phoneNumber2);
        fail("unable to assert, STEPIN");
    }

    @Test
    public void testValidatePhoneNumberIf2() {
        String phoneNumber1 = "Foo";
        String phoneNumber2 = "Bar";
        LocalClass.validatePhoneNumber(phoneNumber1, phoneNumber2);
        fail("unable to assert, STEPIN");
    }

    @Test
    public void testValidatePhoneNumberIf3() {
        String phoneNumber1 = "Foo";
        String phoneNumber2 = "Bar";
        LocalClass.validatePhoneNumber(phoneNumber1, phoneNumber2);
        fail("unable to assert, STEPIN");
    }

    @Test
    public void testValidatePhoneNumberIf4() {
        String phoneNumber1 = "Foo";
        String phoneNumber2 = "Bar";
        LocalClass.validatePhoneNumber(phoneNumber1, phoneNumber2);
        fail("unable to assert, STEPIN");
    }

    @Test
    public void testValidatePhoneNumberIf5() {
        String phoneNumber1 = "Foo";
        String phoneNumber2 = "Bar";
        LocalClass.validatePhoneNumber(phoneNumber1, phoneNumber2);
        fail("unable to assert, STEPIN");
    }

    @Test
    public void testValidatePhoneNumberIf6() {
        String phoneNumber1 = "Foo";
        String phoneNumber2 = "Bar";
        LocalClass.validatePhoneNumber(phoneNumber1, phoneNumber2);
        fail("unable to assert, STEPIN");
    }

    @Test
    public void testValidatePhoneNumberIf7() {
        String phoneNumber1 = "Foo";
        String phoneNumber2 = "Bar";
        LocalClass.validatePhoneNumber(phoneNumber1, phoneNumber2);
        fail("unable to assert, STEPIN");
    }

    @Test
    public void testValidatePhoneNumberIf8() {
        String phoneNumber1 = "Foo";
        String phoneNumber2 = "Bar";
        LocalClass.validatePhoneNumber(phoneNumber1, phoneNumber2);
        fail("unable to assert, STEPIN");
    }
}
