package org.codetab.uknit.itest.variable;

public class AssignParameterToVarTest {
    @InjectMocks
    private AssignParameterToVar assignParameterToVar;

    @BeforeEach
    public void setUp() throws Exception {
        MockitoAnnotations.openMocks(this);
    }

    @Test
    public void testGetStepName() {
        StepInfo stepInfo = Mockito.mock(StepInfo.class);
        StepInfo thisStep = stepInfo;
        String apple = "Foo";

        when(thisStep.getName()).thenReturn(apple);

        String actual = assignParameterToVar.getStepName(stepInfo);

        assertEquals(apple, actual);
    }
}
