package org.codetab.uknit.itest.flow.simple;

import java.util.Map;
import org.codetab.uknit.itest.flow.simple.Model.Pet;
class InferredForEachTest {
    @InjectMocks
    private InferredForEach inferredForEach;

    @BeforeEach
    public void setUp() throws Exception {
        MockitoAnnotations.openMocks(this);
    }

    @Test
    public void testProcess() {
        Map<String, Pet> pets = new HashMap<>();
        String key = "Foo";
        Pet apple = Mockito.mock(Pet.class);
        pets.put(key, apple);
        inferredForEach.process(pets);

        fail("unable to assert, STEPIN");
    }
}
