package org.codetab.uknit.itest.flow.simple;
class SwitchCaseTest {
    @InjectMocks
    private SwitchCase switchCase;

    @BeforeEach
    public void setUp() throws Exception {
        MockitoAnnotations.openMocks(this);
    }

    @Test
    public void testGetMonth() {
        int month = 1;
        String monthString13 = "Invalid month";

        String actual = switchCase.getMonth(month);

        assertEquals(monthString13, actual);
    }
}
