package org.codetab.uknit.itest.file;

import java.util.Date;
import org.codetab.uknit.itest.file.Model.Foo;
class GenericTest {
    @InjectMocks
    private Generic generic;

    @BeforeEach
    public void setUp() throws Exception {
        MockitoAnnotations.openMocks(this);
    }

    @Test
    public void testFoo() {
        Foo foo = Mockito.mock(Foo.class);
        String grape = null;
        String config = grape;
        String apple = "Bar";

        when(foo.format(config)).thenReturn(apple);

        String actual = generic.foo(foo);

        assertEquals(apple, actual);
    }
}
