package org.codetab.uknit.itest.load;

import java.io.File;
import java.util.ArrayList;
import java.util.List;
class SuperGetTest {
    @InjectMocks
    private SuperGet superGet;

    @BeforeEach
    public void setUp() throws Exception {
        MockitoAnnotations.openMocks(this);
    }

    @Test
    public void testGetSuperField() {
        List<File> list = fieldList;
        List<File> fieldList = new ArrayList<>();

        List<File> actual = superGet.getSuperField();

        assertEquals(list, actual);
    }

    @Test
    public void testGetSuperCreatedList() {
        File aFile = STEPIN;

        File actual = superGet.getSuperCreatedList();

        assertEquals(aFile, actual);
    }

    @Test
    public void testGetSuperFieldList() {
        File aFile = STEPIN;

        File actual = superGet.getSuperFieldList();

        assertEquals(aFile, actual);
    }

    @Test
    public void testGetSuperCreatedListInForEach() {
        File aFile = null;

        File actual = superGet.getSuperCreatedListInForEach();

        assertEquals(aFile, actual);
    }

    @Test
    public void testGetSuperFieldListInForEach() {
        File aFile = null;

        File actual = superGet.getSuperFieldListInForEach();

        assertEquals(aFile, actual);
    }
}
