package org.codetab.uknit.itest.brace;

import org.codetab.uknit.itest.brace.Model.Dog;
import org.codetab.uknit.itest.brace.Model.Pets;
class CastTest {
    @InjectMocks
    private Cast cast;

    @Mock
    private Dog fDog;

    @BeforeEach
    public void setUp() throws Exception {
        MockitoAnnotations.openMocks(this);
    }

    @Test
    public void testDeclare() {
        Pets pets = Mockito.mock(Pets.class);
        Dog dog2 = Mockito.mock(Dog.class);
        Dog dog = (Dog) dog2;

        when(pets.getPet("foo")).thenReturn(dog2);

        Dog actual = cast.declare(pets);

        assertSame(dog, actual);
    }

    @Test
    public void testAssign() {
        Pets pets = Mockito.mock(Pets.class);
        Dog dog2 = Mockito.mock(Dog.class);

        when(pets.getPet(("foo"))).thenReturn(dog2);
        cast.assign(pets);

        fail("unable to assert, STEPIN");
    }

    @Test
    public void testAssignToField() {
        Pets pets = Mockito.mock(Pets.class);
        Dog dog = Mockito.mock(Dog.class);

        when(pets.getPet("foo")).thenReturn(dog);
        cast.assignToField(pets);

        fail("unable to assert, STEPIN");
    }

    @Test
    public void testAssignToArray() {
        Pets pets = Mockito.mock(Pets.class);
        Dog dog2 = Mockito.mock(Dog.class);

        when(pets.getPet(("foo"))).thenReturn(dog2);
        cast.assignToArray(pets);

        fail("unable to assert, STEPIN");
    }

    @Test
    public void testAssignToParameterArray() {
        Pets pets = Mockito.mock(Pets.class);
        Dog[] dogs = {};
        Dog dog = Mockito.mock(Dog.class);

        when(pets.getPet(("foo"))).thenReturn(dog);
        cast.assignToParameterArray(pets, dogs);

        fail("unable to assert, STEPIN");
    }
}
