package org.codetab.uknit.itest.extend;

import java.util.concurrent.BlockingQueue;
import org.codetab.uknit.itest.model.MultiLevelMiddle;
import org.codetab.uknit.itest.model.Person;
import org.codetab.uknit.itest.model.QFactory;

public class MultiLevelExtendTest {
    @InjectMocks
    private MultiLevelExtend multiLevelExtend;

    @Mock
    private BlockingQueue<Person> queue;

    @BeforeEach
    public void setUp() throws Exception {
        MockitoAnnotations.openMocks(this);
    }

    @Test
    public void testProcess() throws Exception {
        Person person = Mockito.mock(Person.class);

        when(queue.take()).thenReturn(person);

        Person actual = multiLevelExtend.process();

        assertSame(person, actual);
    }

    @Test
    public void testProcessSameName() throws Exception {
        QFactory qFactory = Mockito.mock(QFactory.class);
        int size = 1;
        BlockingQueue<Person> q = Mockito.mock(BlockingQueue.class);
        Person person = Mockito.mock(Person.class);

        when(qFactory.getQ(size)).thenReturn(q);
        when(q.take()).thenReturn(person);

        Person actual = multiLevelExtend.processSameName(qFactory);

        assertSame(person, actual);
        verify(q).clear();
    }

    @Test
    public void testProcessDiffName() throws Exception {
        QFactory qFactory = Mockito.mock(QFactory.class);
        QFactory queueFactory = qFactory;
        int size = 1;
        BlockingQueue<Person> q = Mockito.mock(BlockingQueue.class);
        Person person = Mockito.mock(Person.class);

        when(queueFactory.getQ(size)).thenReturn(q);
        when(q.take()).thenReturn(person);

        Person actual = multiLevelExtend.processDiffName(qFactory);

        assertSame(person, actual);
        verify(q).clear();
    }
}
