package org.codetab.uknit.jtest.cic;

import java.util.Objects;
import org.codetab.uknit.jtest.cic.ExpNewCreation.Foo.Bar;

public class ExpNewCreationTest {
    @InjectMocks
    private ExpNewCreation expNewCreation;

    @BeforeEach
    public void setUp() throws Exception {
        MockitoAnnotations.openMocks(this);
    }

    @Test
    public void testCreateInnerClass() {
        Bar bar = new Foo().new Bar();

        Bar actual = expNewCreation.createInnerClass();

        assertEquals(bar, actual);
    }

    @Test
    public void testCreateInnerClassFromOuterVar() {
        Bar bar = foo.new Bar();

        Bar actual = expNewCreation.createInnerClassFromOuterVar();

        assertEquals(bar, actual);
    }
}
