package org.codetab.uknit.itest.trycatch;

import java.io.BufferedReader;
import java.io.IOException;
import javax.inject.Inject;

public class TryWithResourceTest {
    @InjectMocks
    private TryWithResource tryWithResource;

    @Mock
    private Logger log;

    @BeforeEach
    public void setUp() throws Exception {
        MockitoAnnotations.openMocks(this);
    }

    @Test
    public void testTryWithResourceTry() throws Exception {
        Io io = Mockito.mock(Io.class);
        BufferedReader br = Mockito.mock(BufferedReader.class);
        String line = "Foo";
        IOException e = Mockito.mock(IOException.class);
        String kiwi = "Bar";

        when(io.bufferedFileReader("foo.txt")).thenReturn(br);
        when(br.readLine()).thenReturn(line);
        tryWithResource.tryWithResource(io);

        verify(log).debug("Line =>" + line);
        verify(e, never()).getMessage();
        verify(log, never()).debug("catch block" + kiwi);
    }

    @Test
    public void testTryWithResourceTryCatchIOException() throws Exception {
        Io io = Mockito.mock(Io.class);
        BufferedReader br = Mockito.mock(BufferedReader.class);
        String line = "Foo";
        IOException e = Mockito.mock(IOException.class);
        String kiwi = "Bar";

        when(io.bufferedFileReader("foo.txt")).thenReturn(br);
        when(br.readLine()).thenReturn(line);
        when(e.getMessage()).thenReturn(kiwi);
        tryWithResource.tryWithResource(io);

        verify(log, never()).debug("Line =>" + line);
        verify(log).debug("catch block" + kiwi);
    }
}
