package org.codetab.uknit.itest.load;

import java.util.Date;
import java.util.List;
class SuperFieldConflictTest {
    @InjectMocks
    private SuperFieldConflict superFieldConflict;

    @Mock
    private Date date;

    @BeforeEach
    public void setUp() throws Exception {
        MockitoAnnotations.openMocks(this);
    }

    @Test
    public void testConflicts() {
        List<Date> dates = new ArrayList<>();
        Date selectedDate = null;
        dates.add(date);

        Date actual = superFieldConflict.conflicts(dates);

        assertEquals(selectedDate, actual);
    }

    @Test
    public void testNoConflict() {
        List<Date> dates = new ArrayList<>();
        Date selectedDate = null;
        Date someDate = Mockito.mock(Date.class);
        dates.add(someDate);

        Date actual = superFieldConflict.noConflict(dates);

        assertEquals(selectedDate, actual);
    }
}
