package org.codetab.uknit.itest.flow.ifelse;

import org.codetab.uknit.itest.flow.ifelse.Model.Duck;
class IfElseIfTest {
    @InjectMocks
    private IfElseIf ifElseIf;

    @BeforeEach
    public void setUp() throws Exception {
        MockitoAnnotations.openMocks(this);
    }

    @Test
    public void testIfElseIfIfCanSwim() {
        Duck duck = Mockito.mock(Duck.class);
        boolean canSwim = true;
        boolean done = true;
        String apple = "Foo";

        when(duck.toString()).thenReturn(apple);

        String actual = ifElseIf.ifElseIf(duck, canSwim, done);

        assertEquals(apple, actual);

        verify(duck).swim("start");
        verify(duck).swim("if canSwim");
        verify(duck, never()).swim("else if canSwim");
        verify(duck).swim("end");
    }

    @Test
    public void testIfElseIfElseCanSwimIfElse() {
        Duck duck = Mockito.mock(Duck.class);
        boolean canSwim = true;
        boolean done = true;
        String apple = "Foo";

        when(duck.toString()).thenReturn(apple);

        String actual = ifElseIf.ifElseIf(duck, canSwim, done);

        assertEquals(apple, actual);

        verify(duck).swim("start");
        verify(duck, never()).swim("if canSwim");
        verify(duck).swim("else if canSwim");
        verify(duck).swim("end");
    }

    @Test
    public void testIfElseIfElseCanSwimElseElse() {
        Duck duck = Mockito.mock(Duck.class);
        boolean canSwim = true;
        boolean done = true;
        String apple = "Foo";

        when(duck.toString()).thenReturn(apple);

        String actual = ifElseIf.ifElseIf(duck, canSwim, done);

        assertEquals(apple, actual);

        verify(duck).swim("start");
        verify(duck, never()).swim("if canSwim");
        verify(duck, never()).swim("else if canSwim");
        verify(duck).swim("end");
    }

    @Test
    public void testIfElseIfElseIfCanSwim() {
        Duck duck = Mockito.mock(Duck.class);
        boolean canSwim = true;
        boolean done = true;
        String apple = "Foo";

        when(duck.toString()).thenReturn(apple);

        String actual = ifElseIf.ifElseIfElse(duck, canSwim, done);

        assertEquals(apple, actual);

        verify(duck).swim("start");
        verify(duck).swim("if canSwim");
        verify(duck, never()).swim("else if done");
        verify(duck, never()).swim("else canSwim done");
        verify(duck).swim("end");
    }

    @Test
    public void testIfElseIfElseElseCanSwimIfElse() {
        Duck duck = Mockito.mock(Duck.class);
        boolean canSwim = true;
        boolean done = true;
        String apple = "Foo";

        when(duck.toString()).thenReturn(apple);

        String actual = ifElseIf.ifElseIfElse(duck, canSwim, done);

        assertEquals(apple, actual);

        verify(duck).swim("start");
        verify(duck, never()).swim("if canSwim");
        verify(duck).swim("else if done");
        verify(duck, never()).swim("else canSwim done");
        verify(duck).swim("end");
    }

    @Test
    public void testIfElseIfElseElseCanSwimElseElse() {
        Duck duck = Mockito.mock(Duck.class);
        boolean canSwim = true;
        boolean done = true;
        String apple = "Foo";

        when(duck.toString()).thenReturn(apple);

        String actual = ifElseIf.ifElseIfElse(duck, canSwim, done);

        assertEquals(apple, actual);

        verify(duck).swim("start");
        verify(duck, never()).swim("if canSwim");
        verify(duck, never()).swim("else if done");
        verify(duck).swim("else canSwim done");
        verify(duck).swim("end");
    }

    @Test
    public void testIfTwiceElseIfIfCanSwim() {
        Duck duck = Mockito.mock(Duck.class);
        boolean canSwim = true;
        boolean canDive = true;
        boolean done = true;
        String apple = "Foo";

        when(duck.toString()).thenReturn(apple);

        String actual = ifElseIf.ifTwiceElseIf(duck, canSwim, canDive, done);

        assertEquals(apple, actual);

        verify(duck).swim("start");
        verify(duck).swim("if canSwim");
        verify(duck, never()).swim("else if  canDive");
        verify(duck, never()).swim("else if done");
        verify(duck).swim("end");
    }

    @Test
    public void testIfTwiceElseIfElseCanSwimIfElse() {
        Duck duck = Mockito.mock(Duck.class);
        boolean canSwim = true;
        boolean canDive = true;
        boolean done = true;
        String apple = "Foo";

        when(duck.toString()).thenReturn(apple);

        String actual = ifElseIf.ifTwiceElseIf(duck, canSwim, canDive, done);

        assertEquals(apple, actual);

        verify(duck).swim("start");
        verify(duck, never()).swim("if canSwim");
        verify(duck).swim("else if  canDive");
        verify(duck, never()).swim("else if done");
        verify(duck).swim("end");
    }

    @Test
    public void testIfTwiceElseIfElseCanSwimElseElseIfElse() {
        Duck duck = Mockito.mock(Duck.class);
        boolean canSwim = true;
        boolean canDive = true;
        boolean done = true;
        String apple = "Foo";

        when(duck.toString()).thenReturn(apple);

        String actual = ifElseIf.ifTwiceElseIf(duck, canSwim, canDive, done);

        assertEquals(apple, actual);

        verify(duck).swim("start");
        verify(duck, never()).swim("if canSwim");
        verify(duck, never()).swim("else if  canDive");
        verify(duck).swim("else if done");
        verify(duck).swim("end");
    }

    @Test
    public void testIfTwiceElseIfElseCanSwimElseElseElseElse() {
        Duck duck = Mockito.mock(Duck.class);
        boolean canSwim = true;
        boolean canDive = true;
        boolean done = true;
        String apple = "Foo";

        when(duck.toString()).thenReturn(apple);

        String actual = ifElseIf.ifTwiceElseIf(duck, canSwim, canDive, done);

        assertEquals(apple, actual);

        verify(duck).swim("start");
        verify(duck, never()).swim("if canSwim");
        verify(duck, never()).swim("else if  canDive");
        verify(duck, never()).swim("else if done");
        verify(duck).swim("end");
    }

    @Test
    public void testIfTwiceElseIfElseIfCanSwim() {
        Duck duck = Mockito.mock(Duck.class);
        boolean canSwim = true;
        boolean canDive = true;
        boolean done = true;
        String apple = "Foo";

        when(duck.toString()).thenReturn(apple);

        String actual = ifElseIf.ifTwiceElseIfElse(duck, canSwim, canDive, done);

        assertEquals(apple, actual);

        verify(duck).swim("start");
        verify(duck).swim("if canSwim");
        verify(duck, never()).swim("else if canDive");
        verify(duck, never()).swim("else if done");
        verify(duck, never()).swim("else");
        verify(duck).swim("end");
    }

    @Test
    public void testIfTwiceElseIfElseElseCanSwimIfElse() {
        Duck duck = Mockito.mock(Duck.class);
        boolean canSwim = true;
        boolean canDive = true;
        boolean done = true;
        String apple = "Foo";

        when(duck.toString()).thenReturn(apple);

        String actual = ifElseIf.ifTwiceElseIfElse(duck, canSwim, canDive, done);

        assertEquals(apple, actual);

        verify(duck).swim("start");
        verify(duck, never()).swim("if canSwim");
        verify(duck).swim("else if canDive");
        verify(duck, never()).swim("else if done");
        verify(duck, never()).swim("else");
        verify(duck).swim("end");
    }

    @Test
    public void testIfTwiceElseIfElseElseCanSwimElseElseIfElse() {
        Duck duck = Mockito.mock(Duck.class);
        boolean canSwim = true;
        boolean canDive = true;
        boolean done = true;
        String apple = "Foo";

        when(duck.toString()).thenReturn(apple);

        String actual = ifElseIf.ifTwiceElseIfElse(duck, canSwim, canDive, done);

        assertEquals(apple, actual);

        verify(duck).swim("start");
        verify(duck, never()).swim("if canSwim");
        verify(duck, never()).swim("else if canDive");
        verify(duck).swim("else if done");
        verify(duck, never()).swim("else");
        verify(duck).swim("end");
    }

    @Test
    public void testIfTwiceElseIfElseElseCanSwimElseElseElseElse() {
        Duck duck = Mockito.mock(Duck.class);
        boolean canSwim = true;
        boolean canDive = true;
        boolean done = true;
        String apple = "Foo";

        when(duck.toString()).thenReturn(apple);

        String actual = ifElseIf.ifTwiceElseIfElse(duck, canSwim, canDive, done);

        assertEquals(apple, actual);

        verify(duck).swim("start");
        verify(duck, never()).swim("if canSwim");
        verify(duck, never()).swim("else if canDive");
        verify(duck, never()).swim("else if done");
        verify(duck).swim("else");
        verify(duck).swim("end");
    }

    @Test
    public void testIfElseIfTwiceIfCanSwimIfCanSwim2() {
        Duck duck = Mockito.mock(Duck.class);
        boolean canSwim = true;
        boolean canDive = true;
        boolean canSwim2 = true;
        boolean canDive2 = true;
        String apple = "Foo";

        when(duck.toString()).thenReturn(apple);

        String actual = ifElseIf.ifElseIfTwice(duck, canSwim, canDive, canSwim2, canDive2);

        assertEquals(apple, actual);

        verify(duck).swim("start");
        verify(duck).swim("if canSwim");
        verify(duck, never()).swim("else if canDive");
        verify(duck).swim("if canSwim2");
        verify(duck, never()).swim("else if canSwim2");
        verify(duck).swim("end");
    }

    @Test
    public void testIfElseIfTwiceIfCanSwimElseCanSwim2IfElse() {
        Duck duck = Mockito.mock(Duck.class);
        boolean canSwim = true;
        boolean canDive = true;
        boolean canSwim2 = true;
        boolean canDive2 = true;
        String apple = "Foo";

        when(duck.toString()).thenReturn(apple);

        String actual = ifElseIf.ifElseIfTwice(duck, canSwim, canDive, canSwim2, canDive2);

        assertEquals(apple, actual);

        verify(duck).swim("start");
        verify(duck).swim("if canSwim");
        verify(duck, never()).swim("else if canDive");
        verify(duck, never()).swim("if canSwim2");
        verify(duck).swim("else if canSwim2");
        verify(duck).swim("end");
    }

    @Test
    public void testIfElseIfTwiceIfCanSwimElseCanSwim2ElseElse() {
        Duck duck = Mockito.mock(Duck.class);
        boolean canSwim = true;
        boolean canDive = true;
        boolean canSwim2 = true;
        boolean canDive2 = true;
        String apple = "Foo";

        when(duck.toString()).thenReturn(apple);

        String actual = ifElseIf.ifElseIfTwice(duck, canSwim, canDive, canSwim2, canDive2);

        assertEquals(apple, actual);

        verify(duck).swim("start");
        verify(duck).swim("if canSwim");
        verify(duck, never()).swim("else if canDive");
        verify(duck, never()).swim("if canSwim2");
        verify(duck, never()).swim("else if canSwim2");
        verify(duck).swim("end");
    }

    @Test
    public void testIfElseIfTwiceElseCanSwimIfElse() {
        Duck duck = Mockito.mock(Duck.class);
        boolean canSwim = true;
        boolean canDive = true;
        boolean canSwim2 = true;
        boolean canDive2 = true;
        String apple = "Foo";

        when(duck.toString()).thenReturn(apple);

        String actual = ifElseIf.ifElseIfTwice(duck, canSwim, canDive, canSwim2, canDive2);

        assertEquals(apple, actual);

        verify(duck).swim("start");
        verify(duck, never()).swim("if canSwim");
        verify(duck).swim("else if canDive");
        verify(duck).swim("if canSwim2");
        verify(duck, never()).swim("else if canSwim2");
        verify(duck).swim("end");
    }

    @Test
    public void testIfElseIfTwiceElseCanSwimElseElse() {
        Duck duck = Mockito.mock(Duck.class);
        boolean canSwim = true;
        boolean canDive = true;
        boolean canSwim2 = true;
        boolean canDive2 = true;
        String apple = "Foo";

        when(duck.toString()).thenReturn(apple);

        String actual = ifElseIf.ifElseIfTwice(duck, canSwim, canDive, canSwim2, canDive2);

        assertEquals(apple, actual);

        verify(duck).swim("start");
        verify(duck, never()).swim("if canSwim");
        verify(duck, never()).swim("else if canDive");
        verify(duck).swim("if canSwim2");
        verify(duck, never()).swim("else if canSwim2");
        verify(duck).swim("end");
    }

    @Test
    public void testIfTwiceElseIfElseTwiceIfCanSwimIfCanSwim2() {
        Duck duck = Mockito.mock(Duck.class);
        boolean canSwim = true;
        boolean canDive = true;
        boolean done = true;
        boolean canSwim2 = true;
        boolean canDive2 = true;
        boolean done2 = true;
        String apple = "Foo";

        when(duck.toString()).thenReturn(apple);

        String actual = ifElseIf.ifTwiceElseIfElseTwice(duck, canSwim, canDive, done, canSwim2, canDive2, done2);

        assertEquals(apple, actual);

        verify(duck).swim("start");
        verify(duck).swim("if canSwim");
        verify(duck, never()).swim("else if canDive");
        verify(duck, never()).swim("else if done");
        verify(duck, never()).swim("else");
        verify(duck).swim("if canSwim2");
        verify(duck, never()).swim("else if canDive2");
        verify(duck, never()).swim("else if done2");
        verify(duck, never()).swim("else 2");
        verify(duck).swim("end");
    }

    @Test
    public void testIfTwiceElseIfElseTwiceIfCanSwimElseCanSwim2IfElse() {
        Duck duck = Mockito.mock(Duck.class);
        boolean canSwim = true;
        boolean canDive = true;
        boolean done = true;
        boolean canSwim2 = true;
        boolean canDive2 = true;
        boolean done2 = true;
        String apple = "Foo";

        when(duck.toString()).thenReturn(apple);

        String actual = ifElseIf.ifTwiceElseIfElseTwice(duck, canSwim, canDive, done, canSwim2, canDive2, done2);

        assertEquals(apple, actual);

        verify(duck).swim("start");
        verify(duck).swim("if canSwim");
        verify(duck, never()).swim("else if canDive");
        verify(duck, never()).swim("else if done");
        verify(duck, never()).swim("else");
        verify(duck, never()).swim("if canSwim2");
        verify(duck).swim("else if canDive2");
        verify(duck, never()).swim("else if done2");
        verify(duck, never()).swim("else 2");
        verify(duck).swim("end");
    }

    @Test
    public void testIfTwiceElseIfElseTwiceElseCanSwim2ElseElseIfElse() {
        Duck duck = Mockito.mock(Duck.class);
        boolean canSwim = true;
        boolean canDive = true;
        boolean done = true;
        boolean canSwim2 = true;
        boolean canDive2 = true;
        boolean done2 = true;
        String apple = "Foo";

        when(duck.toString()).thenReturn(apple);

        String actual = ifElseIf.ifTwiceElseIfElseTwice(duck, canSwim, canDive, done, canSwim2, canDive2, done2);

        assertEquals(apple, actual);

        verify(duck).swim("start");
        verify(duck).swim("if canSwim");
        verify(duck, never()).swim("else if canDive");
        verify(duck, never()).swim("else if done");
        verify(duck, never()).swim("else");
        verify(duck, never()).swim("if canSwim2");
        verify(duck, never()).swim("else if canDive2");
        verify(duck).swim("else if done2");
        verify(duck, never()).swim("else 2");
        verify(duck).swim("end");
    }

    @Test
    public void testIfTwiceElseIfElseTwiceElseCanSwim2ElseElseElseElse() {
        Duck duck = Mockito.mock(Duck.class);
        boolean canSwim = true;
        boolean canDive = true;
        boolean done = true;
        boolean canSwim2 = true;
        boolean canDive2 = true;
        boolean done2 = true;
        String apple = "Foo";

        when(duck.toString()).thenReturn(apple);

        String actual = ifElseIf.ifTwiceElseIfElseTwice(duck, canSwim, canDive, done, canSwim2, canDive2, done2);

        assertEquals(apple, actual);

        verify(duck).swim("start");
        verify(duck).swim("if canSwim");
        verify(duck, never()).swim("else if canDive");
        verify(duck, never()).swim("else if done");
        verify(duck, never()).swim("else");
        verify(duck, never()).swim("if canSwim2");
        verify(duck, never()).swim("else if canDive2");
        verify(duck, never()).swim("else if done2");
        verify(duck).swim("else 2");
        verify(duck).swim("end");
    }

    @Test
    public void testIfTwiceElseIfElseTwiceElseCanSwimIfElse() {
        Duck duck = Mockito.mock(Duck.class);
        boolean canSwim = true;
        boolean canDive = true;
        boolean done = true;
        boolean canSwim2 = true;
        boolean canDive2 = true;
        boolean done2 = true;
        String apple = "Foo";

        when(duck.toString()).thenReturn(apple);

        String actual = ifElseIf.ifTwiceElseIfElseTwice(duck, canSwim, canDive, done, canSwim2, canDive2, done2);

        assertEquals(apple, actual);

        verify(duck).swim("start");
        verify(duck, never()).swim("if canSwim");
        verify(duck).swim("else if canDive");
        verify(duck, never()).swim("else if done");
        verify(duck, never()).swim("else");
        verify(duck).swim("if canSwim2");
        verify(duck, never()).swim("else if canDive2");
        verify(duck, never()).swim("else if done2");
        verify(duck, never()).swim("else 2");
        verify(duck).swim("end");
    }

    @Test
    public void testIfTwiceElseIfElseTwiceElseCanSwimElseElseIfElse() {
        Duck duck = Mockito.mock(Duck.class);
        boolean canSwim = true;
        boolean canDive = true;
        boolean done = true;
        boolean canSwim2 = true;
        boolean canDive2 = true;
        boolean done2 = true;
        String apple = "Foo";

        when(duck.toString()).thenReturn(apple);

        String actual = ifElseIf.ifTwiceElseIfElseTwice(duck, canSwim, canDive, done, canSwim2, canDive2, done2);

        assertEquals(apple, actual);

        verify(duck).swim("start");
        verify(duck, never()).swim("if canSwim");
        verify(duck, never()).swim("else if canDive");
        verify(duck).swim("else if done");
        verify(duck, never()).swim("else");
        verify(duck).swim("if canSwim2");
        verify(duck, never()).swim("else if canDive2");
        verify(duck, never()).swim("else if done2");
        verify(duck, never()).swim("else 2");
        verify(duck).swim("end");
    }

    @Test
    public void testIfTwiceElseIfElseTwiceElseCanSwimElseElseElseElse() {
        Duck duck = Mockito.mock(Duck.class);
        boolean canSwim = true;
        boolean canDive = true;
        boolean done = true;
        boolean canSwim2 = true;
        boolean canDive2 = true;
        boolean done2 = true;
        String apple = "Foo";

        when(duck.toString()).thenReturn(apple);

        String actual = ifElseIf.ifTwiceElseIfElseTwice(duck, canSwim, canDive, done, canSwim2, canDive2, done2);

        assertEquals(apple, actual);

        verify(duck).swim("start");
        verify(duck, never()).swim("if canSwim");
        verify(duck, never()).swim("else if canDive");
        verify(duck, never()).swim("else if done");
        verify(duck).swim("else");
        verify(duck).swim("if canSwim2");
        verify(duck, never()).swim("else if canDive2");
        verify(duck, never()).swim("else if done2");
        verify(duck, never()).swim("else 2");
        verify(duck).swim("end");
    }

    @Test
    public void testIfElseIfPlusIfIfCanSwimIfDone() {
        Duck duck = Mockito.mock(Duck.class);
        boolean canSwim = true;
        boolean canDive = true;
        boolean done = true;
        String apple = "Foo";

        when(duck.toString()).thenReturn(apple);

        String actual = ifElseIf.ifElseIfPlusIf(duck, canSwim, canDive, done);

        assertEquals(apple, actual);

        verify(duck).swim("start");
        verify(duck).swim("if canSwim");
        verify(duck, never()).swim("else if canDive");
        verify(duck).swim("plus if done");
        verify(duck, never()).swim("plus else done");
        verify(duck).swim("end");
    }

    @Test
    public void testIfElseIfPlusIfIfCanSwimElseDone() {
        Duck duck = Mockito.mock(Duck.class);
        boolean canSwim = true;
        boolean canDive = true;
        boolean done = true;
        String apple = "Foo";

        when(duck.toString()).thenReturn(apple);

        String actual = ifElseIf.ifElseIfPlusIf(duck, canSwim, canDive, done);

        assertEquals(apple, actual);

        verify(duck).swim("start");
        verify(duck).swim("if canSwim");
        verify(duck, never()).swim("else if canDive");
        verify(duck, never()).swim("plus if done");
        verify(duck).swim("plus else done");
        verify(duck).swim("end");
    }

    @Test
    public void testIfElseIfPlusIfElseCanSwimIfElse() {
        Duck duck = Mockito.mock(Duck.class);
        boolean canSwim = true;
        boolean canDive = true;
        boolean done = true;
        String apple = "Foo";

        when(duck.toString()).thenReturn(apple);

        String actual = ifElseIf.ifElseIfPlusIf(duck, canSwim, canDive, done);

        assertEquals(apple, actual);

        verify(duck).swim("start");
        verify(duck, never()).swim("if canSwim");
        verify(duck).swim("else if canDive");
        verify(duck).swim("plus if done");
        verify(duck, never()).swim("plus else done");
        verify(duck).swim("end");
    }

    @Test
    public void testIfElseIfPlusIfElseCanSwimElseElse() {
        Duck duck = Mockito.mock(Duck.class);
        boolean canSwim = true;
        boolean canDive = true;
        boolean done = true;
        String apple = "Foo";

        when(duck.toString()).thenReturn(apple);

        String actual = ifElseIf.ifElseIfPlusIf(duck, canSwim, canDive, done);

        assertEquals(apple, actual);

        verify(duck).swim("start");
        verify(duck, never()).swim("if canSwim");
        verify(duck, never()).swim("else if canDive");
        verify(duck).swim("plus if done");
        verify(duck, never()).swim("plus else done");
        verify(duck).swim("end");
    }

    @Test
    public void testIfElseIfElsePlusIfIfCanSwimIfDone() {
        Duck duck = Mockito.mock(Duck.class);
        boolean canSwim = true;
        boolean canDive = true;
        boolean done = true;
        String apple = "Foo";

        when(duck.toString()).thenReturn(apple);

        String actual = ifElseIf.ifElseIfElsePlusIf(duck, canSwim, canDive, done);

        assertEquals(apple, actual);

        verify(duck).swim("start");
        verify(duck).swim("if canSwim");
        verify(duck, never()).swim("else if canDive");
        verify(duck, never()).swim("else");
        verify(duck).swim("plus if done");
        verify(duck, never()).swim("plus else done");
        verify(duck).swim("end");
    }

    @Test
    public void testIfElseIfElsePlusIfIfCanSwimElseDone() {
        Duck duck = Mockito.mock(Duck.class);
        boolean canSwim = true;
        boolean canDive = true;
        boolean done = true;
        String apple = "Foo";

        when(duck.toString()).thenReturn(apple);

        String actual = ifElseIf.ifElseIfElsePlusIf(duck, canSwim, canDive, done);

        assertEquals(apple, actual);

        verify(duck).swim("start");
        verify(duck).swim("if canSwim");
        verify(duck, never()).swim("else if canDive");
        verify(duck, never()).swim("else");
        verify(duck, never()).swim("plus if done");
        verify(duck).swim("plus else done");
        verify(duck).swim("end");
    }

    @Test
    public void testIfElseIfElsePlusIfElseCanSwimIfElse() {
        Duck duck = Mockito.mock(Duck.class);
        boolean canSwim = true;
        boolean canDive = true;
        boolean done = true;
        String apple = "Foo";

        when(duck.toString()).thenReturn(apple);

        String actual = ifElseIf.ifElseIfElsePlusIf(duck, canSwim, canDive, done);

        assertEquals(apple, actual);

        verify(duck).swim("start");
        verify(duck, never()).swim("if canSwim");
        verify(duck).swim("else if canDive");
        verify(duck, never()).swim("else");
        verify(duck).swim("plus if done");
        verify(duck, never()).swim("plus else done");
        verify(duck).swim("end");
    }

    @Test
    public void testIfElseIfElsePlusIfElseCanSwimElseElse() {
        Duck duck = Mockito.mock(Duck.class);
        boolean canSwim = true;
        boolean canDive = true;
        boolean done = true;
        String apple = "Foo";

        when(duck.toString()).thenReturn(apple);

        String actual = ifElseIf.ifElseIfElsePlusIf(duck, canSwim, canDive, done);

        assertEquals(apple, actual);

        verify(duck).swim("start");
        verify(duck, never()).swim("if canSwim");
        verify(duck, never()).swim("else if canDive");
        verify(duck).swim("else");
        verify(duck).swim("plus if done");
        verify(duck, never()).swim("plus else done");
        verify(duck).swim("end");
    }

    @Test
    public void testIfElseIfPlusIfIfCanSwimIfDone2() {
        Duck duck = Mockito.mock(Duck.class);
        boolean canSwim = true;
        boolean canDive = true;
        boolean canFlip = true;
        boolean canFly = true;
        boolean done = true;
        String apple = "Foo";

        when(duck.toString()).thenReturn(apple);

        String actual = ifElseIf.ifElseIfPlusIf(duck, canSwim, canDive, canFlip, canFly, done);

        assertEquals(apple, actual);

        verify(duck).swim("start");
        verify(duck).swim("if canSwim");
        verify(duck, never()).swim("else if canDive");
        verify(duck, never()).swim("if canFlip nest");
        verify(duck, never()).swim("else if canFly nest");
        verify(duck).swim("plus if done");
        verify(duck, never()).swim("plus else done");
        verify(duck).swim("end");
    }

    @Test
    public void testIfElseIfPlusIfIfCanSwimElseDone2() {
        Duck duck = Mockito.mock(Duck.class);
        boolean canSwim = true;
        boolean canDive = true;
        boolean canFlip = true;
        boolean canFly = true;
        boolean done = true;
        String apple = "Foo";

        when(duck.toString()).thenReturn(apple);

        String actual = ifElseIf.ifElseIfPlusIf(duck, canSwim, canDive, canFlip, canFly, done);

        assertEquals(apple, actual);

        verify(duck).swim("start");
        verify(duck).swim("if canSwim");
        verify(duck, never()).swim("else if canDive");
        verify(duck, never()).swim("if canFlip nest");
        verify(duck, never()).swim("else if canFly nest");
        verify(duck, never()).swim("plus if done");
        verify(duck).swim("plus else done");
        verify(duck).swim("end");
    }

    @Test
    public void testIfElseIfPlusIfElseCanSwimIfElseIfCanFlip() {
        Duck duck = Mockito.mock(Duck.class);
        boolean canSwim = true;
        boolean canDive = true;
        boolean canFlip = true;
        boolean canFly = true;
        boolean done = true;
        String apple = "Foo";

        when(duck.toString()).thenReturn(apple);

        String actual = ifElseIf.ifElseIfPlusIf(duck, canSwim, canDive, canFlip, canFly, done);

        assertEquals(apple, actual);

        verify(duck).swim("start");
        verify(duck, never()).swim("if canSwim");
        verify(duck).swim("else if canDive");
        verify(duck).swim("if canFlip nest");
        verify(duck, never()).swim("else if canFly nest");
        verify(duck).swim("plus if done");
        verify(duck, never()).swim("plus else done");
        verify(duck).swim("end");
    }

    @Test
    public void testIfElseIfPlusIfIfElseElseCanFlipIfElse() {
        Duck duck = Mockito.mock(Duck.class);
        boolean canSwim = true;
        boolean canDive = true;
        boolean canFlip = true;
        boolean canFly = true;
        boolean done = true;
        String apple = "Foo";

        when(duck.toString()).thenReturn(apple);

        String actual = ifElseIf.ifElseIfPlusIf(duck, canSwim, canDive, canFlip, canFly, done);

        assertEquals(apple, actual);

        verify(duck).swim("start");
        verify(duck, never()).swim("if canSwim");
        verify(duck).swim("else if canDive");
        verify(duck, never()).swim("if canFlip nest");
        verify(duck).swim("else if canFly nest");
        verify(duck).swim("plus if done");
        verify(duck, never()).swim("plus else done");
        verify(duck).swim("end");
    }

    @Test
    public void testIfElseIfPlusIfIfElseElseCanFlipElseElse() {
        Duck duck = Mockito.mock(Duck.class);
        boolean canSwim = true;
        boolean canDive = true;
        boolean canFlip = true;
        boolean canFly = true;
        boolean done = true;
        String apple = "Foo";

        when(duck.toString()).thenReturn(apple);

        String actual = ifElseIf.ifElseIfPlusIf(duck, canSwim, canDive, canFlip, canFly, done);

        assertEquals(apple, actual);

        verify(duck).swim("start");
        verify(duck, never()).swim("if canSwim");
        verify(duck).swim("else if canDive");
        verify(duck, never()).swim("if canFlip nest");
        verify(duck, never()).swim("else if canFly nest");
        verify(duck).swim("plus if done");
        verify(duck, never()).swim("plus else done");
        verify(duck).swim("end");
    }

    @Test
    public void testIfElseIfPlusIfElseCanSwimElseElse2() {
        Duck duck = Mockito.mock(Duck.class);
        boolean canSwim = true;
        boolean canDive = true;
        boolean canFlip = true;
        boolean canFly = true;
        boolean done = true;
        String apple = "Foo";

        when(duck.toString()).thenReturn(apple);

        String actual = ifElseIf.ifElseIfPlusIf(duck, canSwim, canDive, canFlip, canFly, done);

        assertEquals(apple, actual);

        verify(duck).swim("start");
        verify(duck, never()).swim("if canSwim");
        verify(duck, never()).swim("else if canDive");
        verify(duck, never()).swim("if canFlip nest");
        verify(duck, never()).swim("else if canFly nest");
        verify(duck).swim("plus if done");
        verify(duck, never()).swim("plus else done");
        verify(duck).swim("end");
    }
}
