package org.codetab.uknit.itest.statics;

import org.codetab.uknit.itest.statics.Model.Driver;
import org.codetab.uknit.itest.statics.Model.DriverWait;
class CallsTest {
    @InjectMocks
    private Calls calls;

    @BeforeEach
    public void setUp() throws Exception {
        MockitoAnnotations.openMocks(this);
    }

    @Test
    public void testStaticCallInInit() throws Exception {
        Driver driver = Mockito.mock(Driver.class);
        String timeout = "Foo";
        DriverWait driverWait = new DriverWait(driver, Integer.parseInt(timeout));

        DriverWait actual = calls.staticCallInInit(driver, timeout);

        assertEquals(driverWait, actual);
    }
}
