package org.codetab.uknit.itest.statics;

public class StaticCallsTest {
    @InjectMocks
    private StaticCalls staticCalls;

    @BeforeEach
    public void setUp() throws Exception {
        MockitoAnnotations.openMocks(this);
    }

    @Test
    public void testStaticCallInInit() throws Exception {
        Driver driver = Mockito.mock(Driver.class);
        String timeout = "Foo";
        DriverWait driverWait = new DriverWait(driver, apple);

        DriverWait actual = staticCalls.staticCallInInit(driver, timeout);

        assertSame(driverWait, actual);
    }
}
