package org.codetab.uknit.itest.initializer;

import org.codetab.uknit.itest.initializer.Model.Foo;
class ArrayTest {
    @InjectMocks
    private Array array;

    @BeforeEach
    public void setUp() throws Exception {
        MockitoAnnotations.openMocks(this);
    }

    @Test
    public void testUseArrayAccessInWhen() {
        Foo foo = Mockito.mock(Foo.class);
        String apple = "bar";
        String grape = "Foo";

        when(foo.format(apple)).thenReturn(grape);
        array.useArrayAccessInWhen(foo);

        fail("unable to assert, STEPIN");
    }

    @Test
    public void testUseArrayAccessInVerify() {
        Foo foo = Mockito.mock(Foo.class);
        String apple = "foo";
        array.useArrayAccessInVerify(foo);

        verify(foo).append(apple);
    }
}
