package org.codetab.uknit.itest.initializer;

import org.codetab.uknit.itest.initializer.Model.Foo;
class CyclicTest {
    @InjectMocks
    private Cyclic cyclic;

    @BeforeEach
    public void setUp() throws Exception {
        MockitoAnnotations.openMocks(this);
    }

    @Test
    public void testCyclicInInitializersReal() {
        cyclic.cyclicInInitializersReal();

        fail("unable to assert, STEPIN");
    }

    @Test
    public void testCyclicInInitializersMock() {
        Object foo = Mockito.mock(Object.class);
        Foo value = foo;
        Object result = value;
        String orange = "Foo";
        String apple = "Baz";

        when(result.toString()).thenReturn(orange);

        String actual = cyclic.cyclicInInitializersMock(foo);

        assertEquals(apple, actual);
    }
}
