package org.codetab.uknit.itest.initializer;

import java.util.Locale;

public class RecursiveTest {
    @InjectMocks
    private Recursive recursive;

    @BeforeEach
    public void setUp() throws Exception {
        MockitoAnnotations.openMocks(this);
    }

    @Test
    public void testArray1() {
        int foo = 10;

        int actual = recursive.array1();

        assertEquals(foo, actual);
    }

    @Test
    public void testArray2() {
        int foo = 20;

        int actual = recursive.array2();

        assertEquals(foo, actual);
    }

    @Test
    public void testArray3() {
        int foo = 30;

        int actual = recursive.array3();

        assertEquals(foo, actual);
    }

    @Test
    public void testReturnArrayAccess() {
        int apple = 30;

        int actual = recursive.returnArrayAccess();

        assertEquals(apple, actual);
    }

    @Test
    public void testInvokeInit() {
        Locale locale = Mockito.mock(Locale.class);
        String apple = "Foo";
        String foo = "Bar";

        when(locale.getDisplayName()).thenReturn(apple);

        String actual = recursive.invokeInit(locale);

        assertEquals(foo, actual);
    }
}
