package org.codetab.uknit.itest.anon;

import java.awt.Button;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.function.Predicate;
class AnonTest {
    @InjectMocks
    private Anon anon;

    @BeforeEach
    public void setUp() throws Exception {
        MockitoAnnotations.openMocks(this);
    }

    @Test
    public void testReturnAnon() {

        Thread actual = anon.returnAnon();

        fail("unable to assert, STEPIN");
    }

    @Test
    public void testUseAnon() {
        anon.useAnon();

        fail("unable to assert, STEPIN");
    }

    @Test
    public void testAssignAnon() {

        Predicate<String> actual = anon.assignAnon();

        fail("unable to assert, STEPIN");
    }

    @Test
    public void testAnonFromInterface() {
        StringBuilder sb = Mockito.mock(StringBuilder.class);
        String name = "Foo";
        anon.anonFromInterface(sb, name);

        fail("unable to assert, STEPIN");
    }

    @Test
    public void testReturnAnonFromInterface() {
        StringBuilder sb = Mockito.mock(StringBuilder.class);
        String name = "Foo";

        Runnable actual = anon.returnAnonFromInterface(sb, name);

        fail("unable to assert, STEPIN");
    }

    @Test
    public void testUseAssignedAnonInArg() {
        Button button = Mockito.mock(Button.class);
        anon.useAssignedAnonInArg(button);

        ArgumentCaptor<ActionListener> captorA = ArgumentCaptor.forClass(ActionListener.class);

        verify(button).addActionListener(captorA.capture());
    }

    @Test
    public void testAnonInArg() {
        StringBuilder sb = Mockito.mock(StringBuilder.class);
        StringBuilder stringBuilder = Mockito.mock(StringBuilder.class);

        when(sb.append("finish")).thenReturn(stringBuilder);
        anon.anonInArg(sb);

        fail("unable to assert, STEPIN");
    }

    @Test
    public void testAnonInArgButton() {
        Button button = Mockito.mock(Button.class);
        anon.anonInArg(button);

        ArgumentCaptor<ActionListener> captorA = ArgumentCaptor.forClass(ActionListener.class);

        verify(button).addActionListener(captorA.capture());
    }
}
