package org.codetab.uknit.itest.ret;

import java.time.LocalDate;
class InstOfTest {
    @InjectMocks
    private InstOf instOf;

    @BeforeEach
    public void setUp() throws Exception {
        MockitoAnnotations.openMocks(this);
    }

    @Test
    public void testRet() {
        Object x = Mockito.mock(Object.class);

        boolean actual = instOf.ret(x);

        assertTrue(actual);
    }

    @Test
    public void testRet2() {

        boolean actual = instOf.ret();

        assertTrue(actual);
    }

    @Test
    public void testCall() {

        boolean actual = instOf.call();

        assertTrue(actual);
    }

    @Test
    public void testCallStatic() {

        boolean actual = instOf.callStatic();

        assertTrue(actual);
    }
}
