package org.codetab.uknit.itest.ret;

public class MultiReturnPathNoSplitTest {
    @InjectMocks
    private MultiReturnPathNoSplit multiReturnPathNoSplit;

    @BeforeEach
    public void setUp() throws Exception {
        MockitoAnnotations.openMocks(this);
    }

    @Test
    public void testTwoReturnPaths() {
        String grape = "bar";

        String actual = multiReturnPathNoSplit.twoReturnPaths();

        assertEquals(grape, actual);
    }
}
