package org.codetab.uknit.itest.ret;

public class MultiReturnPathTest {
    @InjectMocks
    private MultiReturnPath multiReturnPath;

    @BeforeEach
    public void setUp() throws Exception {
        MockitoAnnotations.openMocks(this);
    }

    @Test
    public void testTwoReturnPathsIfFlag() {
        String grape = "bar";

        String actual = multiReturnPath.twoReturnPaths();

        assertEquals(grape, actual);
    }

    @Test
    public void testTwoReturnPathsElseFlag() {
        String grape = "bar";

        String actual = multiReturnPath.twoReturnPaths();

        assertEquals(grape, actual);
    }
}
