package org.codetab.uknit.itest.lambda;

public class LambdaInArgTest {
    @InjectMocks
    private LambdaInArg lambdaInArg;

    @BeforeEach
    public void setUp() throws Exception {
        MockitoAnnotations.openMocks(this);
    }

    @Test
    public void testCalculate() {
        CalcA calcA = Mockito.mock(CalcA.class);
        int divValue = 1;
        int apple = 1;

        when(calcA.op(8, 4, any(OperationA.class))).thenReturn(divValue);
        when(calcA.op(6, 3, any(OperationA.class))).thenReturn(apple);

        int actual = lambdaInArg.calculate(calcA);

        assertEquals(apple, actual);

        ArgumentCaptor<OperationA> argcA = ArgumentCaptor.forClass(OperationA.class);
        ArgumentCaptor<OperationA> argcB = ArgumentCaptor.forClass(OperationA.class);
        ArgumentCaptor<OperationA> argcC = ArgumentCaptor.forClass(OperationA.class);
        verify(calcA).op(1, 2, argcA.capture());
        verify(calcA).op(8, 4, argcB.capture());
        verify(calcA).op(6, 3, argcC.capture());
    }
}
