package org.codetab.uknit.jtest.creationref;

import java.util.List;

public class ClassConstructorTest {
    @InjectMocks
    private ClassConstructor classConstructor;

    @Mock
    private Log log;

    @BeforeEach
    public void setUp() throws Exception {
        MockitoAnnotations.openMocks(this);
    }

    @Test
    public void testFoo() {
        List<String> list = new ArrayList<>();
        classConstructor.foo(list);
        fail("unable to assert, STEPIN");
    }
}
