package org.codetab.uknit.itest.generic;

public class InferGenericMapTest {
    @InjectMocks
    private InferGenericMap inferGenericMap;

    @Mock
    private Contacts contacts;
    @Mock
    private ContactsData contactsData;

    @BeforeEach
    public void setUp() throws Exception {
        MockitoAnnotations.openMocks(this);
    }

    @Test
    public void testBuild() {
        Map<String, List<String>> apple = new HashMap<>();

        when(contacts.getContactsMap("foo")).thenReturn(apple);
        inferGenericMap.build();

        verify(contactsData).setContactsMap(apple);
    }
}
