package org.codetab.uknit.itest.optional;

import java.util.Date;
import java.util.List;
import java.util.Optional;

public class OptionalOpsTest {
    @InjectMocks
    private OptionalOps optionalOps;

    @Mock
    private Dates dates;

    @BeforeEach
    public void setUp() throws Exception {
        MockitoAnnotations.openMocks(this);
    }

    @Test
    public void testFooIfDateOIsPresent() {
        Date date = Mockito.mock(Date.class);
        Optional<List<Date>> dateO = Optional.empty();
        String format = "foo";

        when(dates.getDates()).thenReturn(dateO);
        optionalOps.foo(date);

        verify(dates).doSomething(dateO.get(), format);
    }

    @Test
    public void testFooElseDateOIsPresent() {
        Date date = Mockito.mock(Date.class);
        Optional<List<Date>> dateO = Optional.empty();
        String format = "foo";

        when(dates.getDates()).thenReturn(dateO);
        optionalOps.foo(date);

        verify(dates, never()).doSomething(dateO.get(), format);
    }
}
