package org.codetab.uknit.itest.flow.trycatch;

import java.io.BufferedReader;
import java.io.IOException;
import javax.inject.Inject;
import org.codetab.uknit.itest.flow.trycatch.Model.Io;
import org.codetab.uknit.itest.flow.trycatch.Model.Logger;
class TryFinallyCloseResourceTest {
    @InjectMocks
    private TryFinallyCloseResource tryFinallyCloseResource;

    @Mock
    private Logger log;

    @BeforeEach
    public void setUp() throws Exception {
        MockitoAnnotations.openMocks(this);
    }

    @Test
    public void testTryFinallyCloseResourceTryTryIfBr() throws Exception {
        Io io = Mockito.mock(Io.class);
        BufferedReader br = Mockito.mock(BufferedReader.class);
        String line = "Foo";
        String apple = "Bar";
        String grape = "Baz";

        when(io.bufferedFileReader("foo.txt")).thenReturn(br);
        when(br.readLine()).thenReturn(line);
        tryFinallyCloseResource.tryFinallyCloseResource(io);

        verify(log).debug("Entering try block");
        verify(log).debug("Line =>" + line);
        verify(log, never()).debug("IOException in try block =>" + apple);
        verify(log).debug("Entering finally block");
        verify(br).close();
        verify(log, never()).debug("IOException in finally block =>" + grape);
    }

    @Test
    public void testTryFinallyCloseResourceTryTryElseBr() throws Exception {
        Io io = Mockito.mock(Io.class);
        BufferedReader br = Mockito.mock(BufferedReader.class);
        String line = "Foo";
        String apple = "Bar";
        String grape = "Baz";

        when(io.bufferedFileReader("foo.txt")).thenReturn(br);
        when(br.readLine()).thenReturn(line);
        tryFinallyCloseResource.tryFinallyCloseResource(io);

        verify(log).debug("Entering try block");
        verify(log).debug("Line =>" + line);
        verify(log, never()).debug("IOException in try block =>" + apple);
        verify(log).debug("Entering finally block");
        verify(br, never()).close();
        verify(log, never()).debug("IOException in finally block =>" + grape);
    }

    @Test
    public void testTryFinallyCloseResourceTryTryCatchIOException() throws Exception {
        Io io = Mockito.mock(Io.class);
        BufferedReader br = Mockito.mock(BufferedReader.class);
        String line = "Foo";
        String apple = "Bar";
        String grape = "Baz";

        when(io.bufferedFileReader("foo.txt")).thenReturn(br);
        when(br.readLine()).thenReturn(line);
        tryFinallyCloseResource.tryFinallyCloseResource(io);

        verify(log).debug("Entering try block");
        verify(log).debug("Line =>" + line);
        verify(log, never()).debug("IOException in try block =>" + apple);
        verify(log).debug("Entering finally block");
        verify(br, never()).close();
        verify(log).debug("IOException in finally block =>" + grape);
    }

    @Test
    public void testTryFinallyCloseResourceTryCatchIOExceptionTry() throws Exception {
        Io io = Mockito.mock(Io.class);
        BufferedReader br = Mockito.mock(BufferedReader.class);
        String line = "Foo";
        String apple = "Bar";
        String grape = "Baz";

        when(io.bufferedFileReader("foo.txt")).thenReturn(br);
        when(br.readLine()).thenReturn(line);
        tryFinallyCloseResource.tryFinallyCloseResource(io);

        verify(log).debug("Entering try block");
        verify(log, never()).debug("Line =>" + line);
        verify(log).debug("IOException in try block =>" + apple);
        verify(log).debug("Entering finally block");
        verify(br).close();
        verify(log, never()).debug("IOException in finally block =>" + grape);
    }
}
