package org.codetab.uknit.itest.brace.linked;

import java.util.Locale;
import org.codetab.uknit.itest.brace.linked.Model.Foo;
class MockTest {
    @InjectMocks
    private Mock mock;

    @BeforeEach
    public void setUp() throws Exception {
        MockitoAnnotations.openMocks(this);
    }

    @Test
    public void testAssignCreationToMock() {
        Foo foo = Mockito.mock(Foo.class);
        Locale locale = Mockito.mock(Locale.class);
        Locale locale3 = new Locale(("en"));
        Locale locale2 = locale3;

        when(foo.locale()).thenReturn(locale);

        Locale actual = mock.assignCreationToMock(foo);

        assertEquals(locale2, actual);
    }

    @Test
    public void testAssignCreationAndMockToMock() {
        Foo foo = Mockito.mock(Foo.class);
        Locale locale3 = Mockito.mock(Locale.class);
        Locale locale2 = locale3;

        when(foo.locale()).thenReturn(locale3);

        Locale actual = mock.assignCreationAndMockToMock(foo);

        assertSame(locale2, actual);
    }
}
