package org.codetab.uknit.itest.brace.linked;

import java.util.Locale;
import org.codetab.uknit.itest.brace.linked.Model.Foo;

public class UnusedTest {
    @InjectMocks
    private Unused unused;

    @BeforeEach
    public void setUp() throws Exception {
        MockitoAnnotations.openMocks(this);
    }

    @Test
    public void testUnusedButInovked() {
        Foo foo = Mockito.mock(Foo.class);
        Object unObj = Mockito.mock(Object.class);

        when((foo).obj()).thenReturn(unObj);
        unused.unusedButInovked(foo);
    }

    @Test
    public void testUnusedButInovkedAndCreated() {
        Foo foo = Mockito.mock(Foo.class);
        Object unObj = Mockito.mock(Object.class);

        when((foo).obj()).thenReturn(unObj);
        unused.unusedButInovkedAndCreated(foo);
    }
}
