package org.codetab.uknit.itest.imc.vararg;

import org.codetab.uknit.itest.imc.vararg.Model.Foo;
class PrimitivesTest {
    @InjectMocks
    private Primitives primitives;

    @BeforeEach
    public void setUp() throws Exception {
        MockitoAnnotations.openMocks(this);
    }

    @Test
    public void testBooleans() {
        Foo foo = Mockito.mock(Foo.class);
        boolean a = false;
        boolean apple = a;
        boolean orange = a;
        boolean kiwi = va0;
        boolean banana = va0;
        boolean cherry = va2;
        boolean peach = va2;
        boolean fig = va3;
        boolean lychee = va3;
        boolean va0 = false;
        boolean va2 = true;
        boolean va3 = true;
        primitives.booleans(foo);

        verify(foo, times(2)).appendString(String.valueOf(apple));
        verify(foo, times(2)).appendBoolean(orange);
        verify(foo, times(2)).appendString(String.valueOf(cherry));
        verify(foo, times(2)).appendBoolean(peach);
    }

    @Test
    public void testInts() {
        Foo foo = Mockito.mock(Foo.class);
        int apple = va0;
        int orange = va0;
        int kiwi = va2;
        int banana = va2;
        int va0 = 1;
        int va2 = 1;
        primitives.ints(foo);

        verify(foo, times(2)).appendString(String.valueOf(apple));
        verify(foo, times(2)).appendInt(orange);
    }
}
