package org.codetab.uknit.itest.imc.vararg;

import java.util.List;
class VarArgParameterTest {
    @InjectMocks
    private VarArgParameter varArgParameter;

    @BeforeEach
    public void setUp() throws Exception {
        MockitoAnnotations.openMocks(this);
    }

    @Test
    public void testSingleArgForVarArgParam() {
        List<String> names = new ArrayList<>();
        String orange = "Foo";
        String apple = "Bar";
        names.add(orange);

        String actual = varArgParameter.singleArgForVarArgParam(names);

        assertEquals(apple, actual);
    }

    @Test
    public void testMultiArgForVarArgParam() {
        List<String> names = new ArrayList<>();
        String orange = "Foo";
        String apple = "Bar";
        names.add(orange);

        String actual = varArgParameter.multiArgForVarArgParam(names);

        assertEquals(apple, actual);
    }
}
