package org.codetab.uknit.jtest.wildcard;

import java.util.Map;

public class WildcardParameterTest {
    @InjectMocks
    private WildcardParameter wildcardParameter;

    @BeforeEach
    public void setUp() throws Exception {
        MockitoAnnotations.openMocks(this);
    }

    @Test
    public void testFoo() {
        Map<String, ?> source = new HashMap<>();
        String key = "Foo";
        Object value = STEPIN;
        source.put(key, value);
        wildcardParameter.foo(source);
        fail("unable to assert, STEPIN");
    }
}
