package org.codetab.uknit.itest.stream;

import java.util.stream.Collectors.toList;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.Comparator;
import java.util.HashSet;
import java.util.List;
import java.util.Set;
import java.util.stream.Collectors;
import java.util.stream.Stream;
import org.codetab.uknit.itest.model.Album;
import org.codetab.uknit.itest.model.Track;

public class MockStreamTest {
    @InjectMocks
    private MockStream mockStream;

    @BeforeEach
    public void setUp() throws Exception {
        MockitoAnnotations.openMocks(this);
    }

    @Test
    public void testStreamCount() {
        long count = 1L;

        long actual = mockStream.streamCount();

        assertEquals(count, actual);
    }

    @Test
    public void testStreamCountList() {
        List<String> strings = Mockito.mock(List.class);
        Stream<String> apple = Mockito.mock(Stream.class);
        Stream<String> orange = Mockito.mock(Stream.class);
        long count = 1L;

        when(strings.stream()).thenReturn(apple);
        when(apple.filter(any(Predicate.class))).thenReturn(orange);
        when(orange.count()).thenReturn(count);

        long actual = mockStream.streamCount(strings);

        assertEquals(count, actual);

        ArgumentCaptor<Predicate<? super String>> argcA = ArgumentCaptor.forClass(Predicate.class);
        verify(apple).filter(argcA.capture());
    }

    @Test
    public void testStreamCollect() {
        List<String> collected = Stream.of("a", "b", "c").collect(Collectors.toList());

        List<String> actual = mockStream.streamCollect();

        assertEquals(collected, actual);
    }

    @Test
    public void testStreamMapCollect() {
        List<String> collected = Stream.of("a", "b", "hello").map(string -> string.toUpperCase()).collect(toList());

        List<String> actual = mockStream.streamMapCollect();

        assertEquals(collected, actual);
    }

    @Test
    public void testStreamFlatMapCollect() {
        List<Integer> together = Stream.of(Arrays.asList(1, 2), Arrays.asList(3, 4))
                .flatMap(numbers -> numbers.stream()).collect(toList());

        List<Integer> actual = mockStream.streamFlatMapCollect();

        assertEquals(together, actual);
    }

    @Test
    public void testCompare() {
        Track shortestTrack = STEPIN;

        Track actual = mockStream.compare();

        assertEquals(shortestTrack, actual);
    }

    @Test
    public void testFindLongTracks() {
        List<Album> albums = Mockito.mock(List.class);
        Set<String> trackNames = new HashSet<>();
        Stream<Album> apple = Mockito.mock(Stream.class);

        when(albums.stream()).thenReturn(apple);

        Set<String> actual = mockStream.findLongTracks(albums);

        assertEquals(trackNames, actual);
        ArgumentCaptor<Consumer<? super Album>> argcA = ArgumentCaptor.forClass(Consumer.class);
        verify(apple).forEach(argcA.capture());
    }
}
