package org.codetab.uknit.itest.stream;

import java.util.stream.Collectors.toList;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.Comparator;
import java.util.HashSet;
import java.util.List;
import java.util.Set;
import java.util.stream.Collectors;
import java.util.stream.Stream;
import org.codetab.uknit.itest.stream.Model.Album;
import org.codetab.uknit.itest.stream.Model.Track;
class MockStreamTest {
    @InjectMocks
    private MockStream mockStream;

    @BeforeEach
    public void setUp() throws Exception {
        MockitoAnnotations.openMocks(this);
    }

    @Test
    public void testStreamCount() {
        long count = 1L;

        long actual = mockStream.streamCount();

        assertEquals(count, actual);
    }

    @Test
    public void testStreamCountList() {
        List<String> strings = new ArrayList<>();
        Stream<String> stream = Stream.of(STEPIN);
        Stream<String> stream2 = stream.filter(string -> string.isEmpty());
        long count = stream2.count();

        long actual = mockStream.streamCount(strings);

        assertEquals(count, actual);
    }

    @Test
    public void testStreamCollect() {
        List<String> collected = STEPIN;

        List<String> actual = mockStream.streamCollect();

        assertEquals(collected, actual);
    }

    @Test
    public void testStreamMapCollect() {
        List<String> collected = STEPIN;

        List<String> actual = mockStream.streamMapCollect();

        assertEquals(collected, actual);
    }

    @Test
    public void testStreamFlatMapCollect() {
        List<Integer> together = STEPIN;

        List<Integer> actual = mockStream.streamFlatMapCollect();

        assertEquals(together, actual);
    }

    @Test
    public void testCompare() {
        Track shortestTrack = STEPIN;

        Track actual = mockStream.compare();

        assertEquals(shortestTrack, actual);
    }

    @Test
    public void testFindLongTracks() {
        List<Album> albums = new ArrayList<>();
        Set<String> trackNames = new HashSet<>();

        Set<String> actual = mockStream.findLongTracks(albums);

        assertEquals(trackNames, actual);
    }
}
