package org.codetab.uknit.itest.superclass;
class HideSuperFieldTest {
    @InjectMocks
    private HideSuperField hideSuperField;

    @BeforeEach
    public void setUp() throws Exception {
        MockitoAnnotations.openMocks(this);
    }

    @Test
    public void testSetLicensePlate() {
        String license = "Foo";
        hideSuperField.setLicensePlate(license);

        Object actual = hideSuperField.getLicensePlate();

        assertSame(license, actual);
    }

    @Test
    public void testGetLicensePlate() {
        String apple = licensePlate;
        String licensePlate = null;
        hideSuperField.setLicensePlate(licensePlate);

        String actual = hideSuperField.getLicensePlate();

        assertEquals(apple, actual);
    }

    @Test
    public void testUpdateLicensePlate() {
        String license = "Foo";
        hideSuperField.updateLicensePlate(license);

        fail("unable to assert, STEPIN");
    }
}
