package org.codetab.uknit.itest.superclass;

import java.lang.management.ManagementFactory;
import javax.management.MBeanServer;
import javax.management.ObjectName;
class VoidsTest {
    @InjectMocks
    private Voids voids;

    @Mock
    private MBeanServer SERVER;
    @Mock
    private ObjectName objectName;

    @BeforeEach
    public void setUp() throws Exception {
        MockitoAnnotations.openMocks(this);
    }

    @Test
    public void testRegisterMBeanIfServerTry() throws Exception {
        Object object = Mockito.mock(Object.class);
        voids.registerMBean(object);

        verify(SERVER, never()).registerMBean(object, objectName);
    }

    @Test
    public void testRegisterMBeanIfServerTryCatchLinkageError() throws Exception {
        Object object = Mockito.mock(Object.class);
        voids.registerMBean(object);

        verify(SERVER, never()).registerMBean(object, objectName);
    }

    @Test
    public void testRegisterMBeanIfServerTryCatchException() throws Exception {
        Object object = Mockito.mock(Object.class);
        voids.registerMBean(object);

        verify(SERVER, never()).registerMBean(object, objectName);
    }

    @Test
    public void testRegisterMBeanElseServerTry() throws Exception {
        Object object = Mockito.mock(Object.class);
        ObjectInstance objectInstance = Mockito.mock(ObjectInstance.class);

        when(SERVER.registerMBean(object, objectName)).thenReturn(objectInstance);
        voids.registerMBean(object);

        fail("unable to assert, STEPIN");
    }
}
