package org.codetab.uknit.itest.superclass;

public class WithoutWithSuperTest {
    @InjectMocks
    private WithoutWithSuper withoutWithSuper;

    @Mock
    private StringBuilder baz;

    @BeforeEach
    public void setUp() throws Exception {
        MockitoAnnotations.openMocks(this);
    }

    @Test
    public void testAssignPrefix() {
        StringBuilder b = baz;

        StringBuilder actual = withoutWithSuper.assignPrefix();

        assertSame(b, actual);
    }

    @Test
    public void testAssignWithSuperPrefix() {
        StringBuilder b = baz;

        StringBuilder actual = withoutWithSuper.assignWithSuperPrefix();

        assertSame(b, actual);
    }

    @Test
    public void testAssignWithSuperPrefixMultiCall() {
        StringBuilder a = baz;
        StringBuilder b = baz;
        StringBuilder c = baz;
        StringBuilder stringBuilder = Mockito.mock(StringBuilder.class);
        StringBuilder stringBuilder2 = Mockito.mock(StringBuilder.class);

        when(a.append(b)).thenReturn(stringBuilder);
        when(stringBuilder.append(c)).thenReturn(stringBuilder2);

        StringBuilder actual = withoutWithSuper.assignWithSuperPrefixMultiCall();

        assertSame(stringBuilder2, actual);
    }

    @Test
    public void testAssignPrefixMultiCall() {
        StringBuilder a = baz;
        StringBuilder b = baz;
        StringBuilder c = baz;
        StringBuilder stringBuilder = Mockito.mock(StringBuilder.class);
        StringBuilder stringBuilder2 = Mockito.mock(StringBuilder.class);

        when(a.append(b)).thenReturn(stringBuilder);
        when(stringBuilder.append(c)).thenReturn(stringBuilder2);

        StringBuilder actual = withoutWithSuper.assignPrefixMultiCall();

        assertSame(stringBuilder2, actual);
    }

    @Test
    public void testAssignPrefixArg() {
        StringBuilder b = baz;

        StringBuilder actual = withoutWithSuper.assignPrefixArg();

        assertSame(b, actual);
    }

    @Test
    public void testAssignWithSuperPrefixArg() {
        StringBuilder b = baz;

        StringBuilder actual = withoutWithSuper.assignWithSuperPrefixArg();

        assertSame(b, actual);
    }

    @Test
    public void testAssignPrefixArgCall() {
        StringBuilder b = baz;

        StringBuilder actual = withoutWithSuper.assignPrefixArgCall();

        assertSame(b, actual);
    }

    @Test
    public void testAssignWithSuperPrefixArgCall() {
        StringBuilder b = baz;

        StringBuilder actual = withoutWithSuper.assignWithSuperPrefixArgCall();

        assertSame(b, actual);
    }

    @Test
    public void testAssignPrefixArgCallEx1() {
        StringBuilder a = baz;
        StringBuilder stringBuilder = Mockito.mock(StringBuilder.class);
        StringBuilder b = stringBuilder;

        when(baz.append(a)).thenReturn(stringBuilder);

        StringBuilder actual = withoutWithSuper.assignPrefixArgCallEx1();

        assertSame(b, actual);
    }

    @Test
    public void testAssignWithSuperPrefixArgCallEx1() {
        StringBuilder a = baz;
        StringBuilder stringBuilder = Mockito.mock(StringBuilder.class);
        StringBuilder b = stringBuilder;

        when(baz.append(a)).thenReturn(stringBuilder);

        StringBuilder actual = withoutWithSuper.assignWithSuperPrefixArgCallEx1();

        assertSame(b, actual);
    }

    @Test
    public void testAssignPrefixArgCallEx2() {
        StringBuilder stringBuilder = Mockito.mock(StringBuilder.class);
        StringBuilder b = stringBuilder;

        when(baz.append(baz)).thenReturn(stringBuilder);

        StringBuilder actual = withoutWithSuper.assignPrefixArgCallEx2();

        assertSame(b, actual);
    }

    @Test
    public void testAssignWithSuperPrefixArgCallEx2() {
        StringBuilder stringBuilder = Mockito.mock(StringBuilder.class);
        StringBuilder b = stringBuilder;

        when(baz.append(baz)).thenReturn(stringBuilder);

        StringBuilder actual = withoutWithSuper.assignWithSuperPrefixArgCallEx2();

        assertSame(b, actual);
    }
}
