package org.codetab.uknit.itest.internal;

import java.text.DateFormat;
import java.text.ParseException;
import java.time.Instant;
import java.util.Date;

public class CallInternalWithInternalArgTest {
    @InjectMocks
    private CallInternalWithInternalArg callInternalWithInternalArg;

    @BeforeEach
    public void setUp() throws Exception {
        MockitoAnnotations.openMocks(this);
    }

    @Test
    public void testCallA() {
        Date date = Mockito.mock(Date.class);
        Instant instant = Mockito.mock(Instant.class);
        int apple = 1;

        when(date.toInstant()).thenReturn(instant);
        when(instant.getNano()).thenReturn(apple);

        int actual = callInternalWithInternalArg.callA(date);

        assertEquals(apple, actual);
    }

    @Test
    public void testCallB() throws Exception {
        DateFormat dateFormat = Mockito.mock(DateFormat.class);
        String dateStr1 = "Foo";
        Date date2 = Mockito.mock(Date.class);
        Date date = Mockito.mock(Date.class);
        boolean apple = true;

        when(dateFormat.parse(dateStr1)).thenReturn(date);
        when(date.after(date2)).thenReturn(apple);

        boolean actual = callInternalWithInternalArg.callB(dateFormat, dateStr1, date2);

        assertTrue(actual);
    }

    @Test
    public void testMockDiffNameC() {
        Instant instant = Mockito.mock(Instant.class);
        Instant instant2 = Mockito.mock(Instant.class);
        Instant instant3 = Mockito.mock(Instant.class);
        Instant instant4 = Mockito.mock(Instant.class);

        when(instant.minusMillis(1)).thenReturn(instant2);
        when(instant2.minusMillis(2)).thenReturn(instant3);
        when(instant3.minusMillis(3)).thenReturn(instant4);

        Instant actual = callInternalWithInternalArg.mockDiffNameC(instant);

        assertSame(instant4, actual);
    }

    @Test
    public void testMockSameNameD() {
        Instant instant = Mockito.mock(Instant.class);
        Instant instant2 = Mockito.mock(Instant.class);
        Instant instant3 = Mockito.mock(Instant.class);
        Instant instant4 = Mockito.mock(Instant.class);

        when(instant.minusMillis(4)).thenReturn(instant2);
        when(instant2.minusMillis(5)).thenReturn(instant3);
        when(instant3.minusMillis(6)).thenReturn(instant4);

        Instant actual = callInternalWithInternalArg.mockSameNameD(instant);

        assertSame(instant4, actual);
    }

    @Test
    public void testRealDiffNameE() {
        String str = "Foo";
        String orange = "Bar";

        String actual = callInternalWithInternalArg.realDiffNameE(str);

        assertEquals(orange, actual);
    }

    @Test
    public void testRealSameNameF() {
        String str = "Foo";
        String orange = "Bar";

        String actual = callInternalWithInternalArg.realSameNameF(str);

        assertEquals(orange, actual);
    }
}
