package org.codetab.uknit.itest.internal;

import java.util.Objects.isNull;
import java.util.Date;

public class CallNotInCtlPathTest {
    @InjectMocks
    private CallNotInCtlPath callNotInCtlPath;

    @Mock
    private Payload payload;

    @BeforeEach
    public void setUp() throws Exception {
        MockitoAnnotations.openMocks(this);
    }

    @Test
    public void testCallNotInPathIfIsNull() {
        Date date2 = Mockito.mock(Date.class);

        when(payload.getDate()).thenReturn(date2);

        Date actual = callNotInCtlPath.callNotInPath();

        assertSame(date2, actual);
    }

    @Test
    public void testCallNotInPathElseIsNull() {
        Date date2 = Mockito.mock(Date.class);

        when(payload.getDate()).thenReturn(date2);

        Date actual = callNotInCtlPath.callNotInPath();

        assertSame(date2, actual);
    }
}
