package org.codetab.uknit.itest.generic;

import java.io.PrintWriter;
import java.util.List;
class WildcardCaptureTest {
    @InjectMocks
    private WildcardCapture wildcardCapture;

    @BeforeEach
    public void setUp() throws Exception {
        MockitoAnnotations.openMocks(this);
    }

    @Test
    public void testWrite() {
        PrintWriter out = Mockito.mock(PrintWriter.class);
        List<?> value = new ArrayList<>();
        wildcardCapture.write(out, value);

        fail("unable to assert, STEPIN");
    }
}
