package org.codetab.uknit.jtest.svd;

import java.util.Map;

public class VarargsTest {
    @InjectMocks
    private Varargs varargs;

    @BeforeEach
    public void setUp() throws Exception {
        MockitoAnnotations.openMocks(this);
    }

    @Test
    public void testCallWithArrayOfAnotherName() {
        Map<String, String> names = new HashMap<>();
        String key = "Foo";
        String name = "Bar";
        names.put(key, name);

        String actual = varargs.callWithArrayOfAnotherName(names);

        assertEquals(name, actual);
    }

    @Test
    public void testCallWithArrayOfSameName() {
        Map<String, String> names = new HashMap<>();
        String key = "Foo";
        String name = "Bar";
        names.put(key, name);

        String actual = varargs.callWithArrayOfSameName(names);

        assertEquals(name, actual);
    }

    @Test
    public void testMethodWithVarargs() {
        Map<String, String> names = new HashMap<>();
        String[] keys = {};
        String apple = "Foo";
        String grape = "Bar";
        names.put(apple, grape);

        String actual = varargs.methodWithVarargs(names, keys);

        assertEquals(grape, actual);
    }
}
