package org.codetab.uknit.itest.invoke;

import java.time.LocalDate;
import java.util.Calendar;
import java.util.Date;

public class CallStaticTest {
    @InjectMocks
    private CallStatic callStatic;

    @BeforeEach
    public void setUp() throws Exception {
        MockitoAnnotations.openMocks(this);
    }

    @Test
    public void testCallStatic() {
        LocalDate date = Mockito.mock(LocalDate.class);
        int apple = 1;

        when(date.compareTo(LocalDate.now())).thenReturn(apple);

        int actual = callStatic.callStatic(date);

        assertEquals(apple, actual);
    }

    @Test
    public void testStaticCallReturn() {

        Date actual = callStatic.staticCallReturn();
        fail("unable to assert, STEPIN");
    }

    @Test
    public void testRealCallReturn() {

        Date actual = callStatic.realCallReturn();
        fail("unable to assert, STEPIN");
    }
}
