package org.codetab.uknit.itest.invoke;

import java.io.File;

public class InferredVarTest {
    @InjectMocks
    private InferredVar inferredVar;

    @BeforeEach
    public void setUp() throws Exception {
        MockitoAnnotations.openMocks(this);
    }

    @Test
    public void testAppend() {
        StringBuilder s1 = Mockito.mock(StringBuilder.class);
        StringBuilder s2 = Mockito.mock(StringBuilder.class);
        File file = Mockito.mock(File.class);
        String apple = "Foo";
        StringBuilder orange = Mockito.mock(StringBuilder.class);
        StringBuilder kiwi = Mockito.mock(StringBuilder.class);

        when(file.getName()).thenReturn(apple);
        when(s2.append(apple.toLowerCase())).thenReturn(orange);
        when(s1.append(orange)).thenReturn(kiwi);

        StringBuilder actual = inferredVar.append(s1, s2, file);

        assertSame(kiwi, actual);
    }
}
