package org.codetab.uknit.itest.invoke;

import java.io.File;

public class InferredVarTest {
    @InjectMocks
    private InferredVar inferredVar;

    @BeforeEach
    public void setUp() throws Exception {
        MockitoAnnotations.openMocks(this);
    }

    @Test
    public void testChainedCall() {
        StringBuilder s1 = Mockito.mock(StringBuilder.class);
        StringBuilder s2 = Mockito.mock(StringBuilder.class);
        File file = Mockito.mock(File.class);
        String apple = "Foo";
        StringBuilder grape = Mockito.mock(StringBuilder.class);
        StringBuilder orange = Mockito.mock(StringBuilder.class);

        when(file.getName()).thenReturn(apple);
        when(s2.append(apple.toLowerCase())).thenReturn(grape);
        when(s1.append(grape)).thenReturn(orange);

        StringBuilder actual = inferredVar.chainedCall(s1, s2, file);

        assertSame(orange, actual);
    }

    @Test
    public void testMultiInvokeArgs() {
        Person person = Mockito.mock(Person.class);
        Address address = Mockito.mock(Address.class);
        String apple = "Foo";
        String grape = "Bar";

        when(person.getName()).thenReturn(apple);
        when(person.getCity()).thenReturn(grape);
        inferredVar.multiInvokeArgs(person, address);

        verify(address).setAddress(apple, grape);
    }
}
