package org.codetab.uknit.itest.invoke;

public class MiThisTest {
    @InjectMocks
    private MiThis miThis;

    @Mock
    private Helper helper;

    @BeforeEach
    public void setUp() throws Exception {
        MockitoAnnotations.openMocks(this);
    }

    @Test
    public void testThisArg() {
        Document document = Mockito.mock(Document.class);

        when(helper.getDocument(this, "foo")).thenReturn(document);

        Document actual = miThis.thisArg();

        assertSame(document, actual);
    }

    @Test
    public void testThisInvoke() {
        Document document = Mockito.mock(Document.class);

        Document actual = miThis.thisInvoke();

        assertSame(document, actual);
    }
}
