package org.codetab.uknit.itest.invoke;

import java.io.File;
import org.codetab.uknit.itest.invoke.Model.Foo;
class SameInstanceTest {
    @InjectMocks
    private SameInstance sameInstance;

    @BeforeEach
    public void setUp() throws Exception {
        MockitoAnnotations.openMocks(this);
    }

    @Test
    public void testInvokeOnSameInstance() {
        Foo foo = Mockito.mock(Foo.class);
        File f1 = Mockito.mock(File.class);
        File f2 = Mockito.mock(File.class);
        File a = f1;
        File c = f2;
        String apple = "Foo";
        String grape = "Bar";
        String orange = "Baz";
        String kiwi = "Qux";
        String mango = "Quux";
        String banana = "Corge";

        when(a.getAbsolutePath()).thenReturn(apple).thenReturn(grape).thenReturn(orange).thenReturn(kiwi)
                .thenReturn(mango);
        when(c.getAbsolutePath()).thenReturn(banana);
        sameInstance.invokeOnSameInstance(foo, f1, f2);

        verify(foo).appendString(apple);
        verify(foo).appendString(grape);
        verify(foo).appendString(orange);
        verify(foo).appendString(kiwi);
        verify(foo).appendString(mango);
        verify(foo).appendString(banana);
    }
}
