package org.codetab.uknit.itest.invoke;

public class TryCatchTest {
    @InjectMocks
    private TryCatch tryCatch;

    @Mock
    private DataDao dataDao;
    @Mock
    private Document document;

    @BeforeEach
    public void setUp() throws Exception {
        MockitoAnnotations.openMocks(this);
    }

    @Test
    public void testCallSameMethodInTryAndCatchTry() {
        long apple = 1L;
        long grape = 1L;

        when(document.getLocatorId()).thenReturn(apple);
        tryCatch.callSameMethodInTryAndCatch();

        verify(dataDao).get(apple);
        verify(document, never()).getLocatorId();
        verify(dataDao, never()).delete(grape);
    }

    @Test
    public void testCallSameMethodInTryAndCatchTryCatchIllegalStateException() {
        long apple = 1L;
        long grape = 1L;

        when(document.getLocatorId()).thenReturn(apple).thenReturn(grape);
        tryCatch.callSameMethodInTryAndCatch();

        verify(dataDao).get(apple);
        verify(dataDao).delete(grape);
    }
}
