package org.codetab.uknit.itest.flow.ifelse;

import org.codetab.uknit.itest.flow.ifelse.Model.Duck;
class IfElseTest {
    @InjectMocks
    private IfElse ifElse;

    @BeforeEach
    public void setUp() throws Exception {
        MockitoAnnotations.openMocks(this);
    }

    @Test
    public void testIfFooIfCanSwim() {
        Duck duck = Mockito.mock(Duck.class);
        boolean canSwim = true;
        String apple = "Foo";

        when(duck.toString()).thenReturn(apple);

        String actual = ifElse.ifFoo(duck, canSwim);

        assertEquals(apple, actual);

        verify(duck).swim("start");
        verify(duck).swim("if");
        verify(duck).swim("end");
    }

    @Test
    public void testIfFooElseCanSwim() {
        Duck duck = Mockito.mock(Duck.class);
        boolean canSwim = true;
        String apple = "Foo";

        when(duck.toString()).thenReturn(apple);

        String actual = ifElse.ifFoo(duck, canSwim);

        assertEquals(apple, actual);

        verify(duck).swim("start");
        verify(duck, never()).swim("if");
        verify(duck).swim("end");
    }

    @Test
    public void testIfElseFooIfCanSwim() {
        Duck duck = Mockito.mock(Duck.class);
        boolean canSwim = true;
        String apple = "Foo";

        when(duck.toString()).thenReturn(apple);

        String actual = ifElse.ifElseFoo(duck, canSwim);

        assertEquals(apple, actual);

        verify(duck).swim("start");
        verify(duck).swim("if");
        verify(duck, never()).swim("else");
        verify(duck).swim("end");
    }

    @Test
    public void testIfElseFooElseCanSwim() {
        Duck duck = Mockito.mock(Duck.class);
        boolean canSwim = true;
        String apple = "Foo";

        when(duck.toString()).thenReturn(apple);

        String actual = ifElse.ifElseFoo(duck, canSwim);

        assertEquals(apple, actual);

        verify(duck).swim("start");
        verify(duck, never()).swim("if");
        verify(duck).swim("else");
        verify(duck).swim("end");
    }

    @Test
    public void testIfNestIfFooIfCanSwimIfDone() {
        Duck duck = Mockito.mock(Duck.class);
        boolean canSwim = true;
        boolean done = true;
        String apple = "Foo";

        when(duck.toString()).thenReturn(apple);

        String actual = ifElse.ifNestIfFoo(duck, canSwim, done);

        assertEquals(apple, actual);

        verify(duck).swim("start");
        verify(duck).swim("if");
        verify(duck).swim("if if");
        verify(duck, never()).swim("if else");
        verify(duck, never()).swim("else");
        verify(duck).swim("end");
    }

    @Test
    public void testIfNestIfFooIfCanSwimElseDone() {
        Duck duck = Mockito.mock(Duck.class);
        boolean canSwim = true;
        boolean done = true;
        String apple = "Foo";

        when(duck.toString()).thenReturn(apple);

        String actual = ifElse.ifNestIfFoo(duck, canSwim, done);

        assertEquals(apple, actual);

        verify(duck).swim("start");
        verify(duck).swim("if");
        verify(duck, never()).swim("if if");
        verify(duck).swim("if else");
        verify(duck, never()).swim("else");
        verify(duck).swim("end");
    }

    @Test
    public void testIfNestIfFooElseCanSwim() {
        Duck duck = Mockito.mock(Duck.class);
        boolean canSwim = true;
        boolean done = true;
        String apple = "Foo";

        when(duck.toString()).thenReturn(apple);

        String actual = ifElse.ifNestIfFoo(duck, canSwim, done);

        assertEquals(apple, actual);

        verify(duck).swim("start");
        verify(duck, never()).swim("if");
        verify(duck, never()).swim("if if");
        verify(duck, never()).swim("if else");
        verify(duck).swim("else");
        verify(duck).swim("end");
    }

    @Test
    public void testIfIfFooIfCanSwimIfDone() {
        Duck duck = Mockito.mock(Duck.class);
        boolean canSwim = true;
        boolean done = true;
        String apple = "Foo";

        when(duck.toString()).thenReturn(apple);

        String actual = ifElse.ifIfFoo(duck, canSwim, done);

        assertEquals(apple, actual);

        verify(duck).swim("start");
        verify(duck).swim("if");
        verify(duck, never()).swim("else");
        verify(duck).swim("if if");
        verify(duck, never()).swim("if else");
        verify(duck).swim("end");
    }

    @Test
    public void testIfIfFooIfCanSwimElseDone() {
        Duck duck = Mockito.mock(Duck.class);
        boolean canSwim = true;
        boolean done = true;
        String apple = "Foo";

        when(duck.toString()).thenReturn(apple);

        String actual = ifElse.ifIfFoo(duck, canSwim, done);

        assertEquals(apple, actual);

        verify(duck).swim("start");
        verify(duck).swim("if");
        verify(duck, never()).swim("else");
        verify(duck, never()).swim("if if");
        verify(duck).swim("if else");
        verify(duck).swim("end");
    }

    @Test
    public void testIfIfFooElseCanSwim() {
        Duck duck = Mockito.mock(Duck.class);
        boolean canSwim = true;
        boolean done = true;
        String apple = "Foo";

        when(duck.toString()).thenReturn(apple);

        String actual = ifElse.ifIfFoo(duck, canSwim, done);

        assertEquals(apple, actual);

        verify(duck).swim("start");
        verify(duck, never()).swim("if");
        verify(duck).swim("else");
        verify(duck).swim("if if");
        verify(duck, never()).swim("if else");
        verify(duck).swim("end");
    }

    @Test
    public void testIfNestIfIfFooIfCanSwimIfCanDiveIfDone() {
        Duck duck = Mockito.mock(Duck.class);
        boolean canSwim = true;
        boolean canDive = true;
        boolean done = true;
        String apple = "Foo";

        when(duck.toString()).thenReturn(apple);

        String actual = ifElse.ifNestIfIfFoo(duck, canSwim, canDive, done);

        assertEquals(apple, actual);

        verify(duck).swim("start");
        verify(duck).swim("if");
        verify(duck).swim("nest if");
        verify(duck, never()).swim("nest else");
        verify(duck).swim("nest if if");
        verify(duck, never()).swim("nest if else");
        verify(duck, never()).swim("else");
        verify(duck).swim("end");
    }

    @Test
    public void testIfNestIfIfFooIfCanSwimIfCanDiveElseDone() {
        Duck duck = Mockito.mock(Duck.class);
        boolean canSwim = true;
        boolean canDive = true;
        boolean done = true;
        String apple = "Foo";

        when(duck.toString()).thenReturn(apple);

        String actual = ifElse.ifNestIfIfFoo(duck, canSwim, canDive, done);

        assertEquals(apple, actual);

        verify(duck).swim("start");
        verify(duck).swim("if");
        verify(duck).swim("nest if");
        verify(duck, never()).swim("nest else");
        verify(duck, never()).swim("nest if if");
        verify(duck).swim("nest if else");
        verify(duck, never()).swim("else");
        verify(duck).swim("end");
    }

    @Test
    public void testIfNestIfIfFooIfCanSwimElseCanDive() {
        Duck duck = Mockito.mock(Duck.class);
        boolean canSwim = true;
        boolean canDive = true;
        boolean done = true;
        String apple = "Foo";

        when(duck.toString()).thenReturn(apple);

        String actual = ifElse.ifNestIfIfFoo(duck, canSwim, canDive, done);

        assertEquals(apple, actual);

        verify(duck).swim("start");
        verify(duck).swim("if");
        verify(duck, never()).swim("nest if");
        verify(duck).swim("nest else");
        verify(duck).swim("nest if if");
        verify(duck, never()).swim("nest if else");
        verify(duck, never()).swim("else");
        verify(duck).swim("end");
    }

    @Test
    public void testIfNestIfIfFooElseCanSwim() {
        Duck duck = Mockito.mock(Duck.class);
        boolean canSwim = true;
        boolean canDive = true;
        boolean done = true;
        String apple = "Foo";

        when(duck.toString()).thenReturn(apple);

        String actual = ifElse.ifNestIfIfFoo(duck, canSwim, canDive, done);

        assertEquals(apple, actual);

        verify(duck).swim("start");
        verify(duck, never()).swim("if");
        verify(duck, never()).swim("nest if");
        verify(duck, never()).swim("nest else");
        verify(duck, never()).swim("nest if if");
        verify(duck, never()).swim("nest if else");
        verify(duck).swim("else");
        verify(duck).swim("end");
    }
}
