package org.codetab.uknit.itest.cast;

import org.codetab.uknit.itest.model.Dog;
import org.codetab.uknit.itest.model.Pets;

public class CastExpTest {
    @InjectMocks
    private CastExp castExp;

    @BeforeEach
    public void setUp() throws Exception {
        MockitoAnnotations.openMocks(this);
    }

    @Test
    public void testDeclare() {
        Pets pets = Mockito.mock(Pets.class);
        Dog dog = Mockito.mock(Dog.class);

        when(pets.getPet("foo")).thenReturn(dog);
        castExp.declare(pets);
        fail("unable to assert, STEPIN");
    }
}
