package org.codetab.uknit.itest.cast;

import org.codetab.uknit.itest.cast.Model.Dog;
import org.codetab.uknit.itest.cast.Model.Pets;
class CastTest {
    @InjectMocks
    private Cast cast;

    @Mock
    private Dog fDog;

    @BeforeEach
    public void setUp() throws Exception {
        MockitoAnnotations.openMocks(this);
    }

    @Test
    public void testDeclare() {
        Pets pets = Mockito.mock(Pets.class);
        Dog dog2 = Mockito.mock(Dog.class);

        when(pets.getPet("foo")).thenReturn(dog2);
        cast.declare(pets);

        fail("unable to assert, STEPIN");
    }

    @Test
    public void testAssign() {
        Pets pets = Mockito.mock(Pets.class);
        Dog dog2 = Mockito.mock(Dog.class);

        when(pets.getPet("foo")).thenReturn(dog2);
        cast.assign(pets);

        fail("unable to assert, STEPIN");
    }

    @Test
    public void testAssignToField() {
        Pets pets = Mockito.mock(Pets.class);
        Dog dog = Mockito.mock(Dog.class);

        when(pets.getPet("foo")).thenReturn(dog);
        cast.assignToField(pets);

        fail("unable to assert, STEPIN");
    }

    @Test
    public void testAssignToArray() {
        Pets pets = Mockito.mock(Pets.class);
        Dog dog = Mockito.mock(Dog.class);

        when(pets.getPet("foo")).thenReturn(dog);
        cast.assignToArray(pets);

        fail("unable to assert, STEPIN");
    }

    @Test
    public void testAssignToParameterArray() {
        Pets pets = Mockito.mock(Pets.class);
        Dog[] dogs = {};
        Dog dog = Mockito.mock(Dog.class);

        when(pets.getPet("foo")).thenReturn(dog);
        cast.assignToParameterArray(pets, dogs);

        fail("unable to assert, STEPIN");
    }
}
