package org.codetab.uknit.itest.cast;

import org.codetab.uknit.itest.cast.Model.Foo;
class ParamTest {
    @InjectMocks
    private Param param;

    @BeforeEach
    public void setUp() throws Exception {
        MockitoAnnotations.openMocks(this);
    }

    @Test
    public void testCastParam() {
        Foo foo = Mockito.mock(Foo.class);
        Foo fooObj = Mockito.mock(Foo.class);
        Object count = Mockito.mock(Object.class);
        int apple = 1;
        int grape = 1;

        when(((Foo) fooObj).index()).thenReturn(apple).thenReturn(grape);
        param.castParam(foo, fooObj, count);

        verify(foo).append(apple);
        verify(foo).append(grape);
    }
}
