package org.codetab.uknit.itest.cast;

import org.codetab.uknit.itest.cast.Model.Metric;
class TypeChangeTest {
    @InjectMocks
    private TypeChange typeChange;

    @BeforeEach
    public void setUp() throws Exception {
        MockitoAnnotations.openMocks(this);
    }

    @Test
    public void testGetCount() {
        long count = 1L;

        long actual = typeChange.getCount();

        assertEquals(count, actual);
    }

    @Test
    public void testAggregate() {
        TypeChange other = Mockito.mock(TypeChange.class);
        long count = 1L;

        when(((TypeChange) other).getCount()).thenReturn(count);
        typeChange.aggregate(other);

        fail("unable to assert, STEPIN");
    }
}
