package org.codetab.uknit.itest.misuse;

import java.io.File;
class HashCodeTest {
    @InjectMocks
    private HashCode hashCode;

    @BeforeEach
    public void setUp() throws Exception {
        MockitoAnnotations.openMocks(this);
    }

    @Test
    public void testFoo() {
        File file1 = Mockito.mock(File.class);
        File file2 = Mockito.mock(File.class);

        boolean actual = hashCode.foo(file1, file2);

        assertTrue(actual);
    }
}
