package org.codetab.uknit.itest.misuse;

import org.codetab.uknit.itest.misuse.Model.Duck;
class ToStringTest {
    @InjectMocks
    private ToString toString;

    @BeforeEach
    public void setUp() throws Exception {
        MockitoAnnotations.openMocks(this);
    }

    @Test
    public void testToStringNotAllowedInVerifyIfCanSwim() {
        Duck duck = Mockito.mock(Duck.class);
        boolean canSwim = true;
        String grape = "Foo";

        when(duck.toString()).thenReturn(grape);

        String actual = toString.toStringNotAllowedInVerify(duck, canSwim);

        assertEquals(grape, actual);
    }

    @Test
    public void testToStringNotAllowedInVerifyElseCanSwim() {
        Duck duck = Mockito.mock(Duck.class);
        boolean canSwim = true;
        String grape = "Bar";

        when(duck.toString()).thenReturn(grape);

        String actual = toString.toStringNotAllowedInVerify(duck, canSwim);

        assertEquals(grape, actual);
    }
}
