package org.codetab.uknit.itest.flow;

public class DoWhileTest {
    @InjectMocks
    private DoWhile doWhile;

    @BeforeEach
    public void setUp() throws Exception {
        MockitoAnnotations.openMocks(this);
    }

    @Test
    public void testWhileDo() {
        int count = 1;

        int actual = doWhile.whileDo();

        assertEquals(count, actual);
    }

    @Test
    public void testDoWhile() {
        int count = 1;

        int actual = doWhile.doWhile();

        assertEquals(count, actual);
    }
}
