package org.codetab.uknit.itest.flow;

import java.util.Objects.isNull;
import java.util.List;

public class ForEachIfTest {
    @InjectMocks
    private ForEachIf forEachIf;

    @BeforeEach
    public void setUp() throws Exception {
        MockitoAnnotations.openMocks(this);
    }

    @Test
    public void testAddOrderIfAbsentIfIsNull() {
        List<YmlNode> itemsList = new ArrayList<>();
        YmlNode items = Mockito.mock(YmlNode.class);
        List<YmlNode> itemList = new ArrayList<>();
        int i = 0;
        YmlNode item = Mockito.mock(YmlNode.class);
        Object kiwi = Mockito.mock(Object.class);
        itemsList.add(items);
        itemList.add(item);

        when(items.findValues("item")).thenReturn(itemList);
        when(item.findValue("order")).thenReturn(kiwi);
        forEachIf.addOrderIfAbsent(itemsList);

        verify(item).put("order", i);
    }

    @Test
    public void testAddOrderIfAbsentElseIsNull() {
        List<YmlNode> itemsList = new ArrayList<>();
        YmlNode items = Mockito.mock(YmlNode.class);
        List<YmlNode> itemList = new ArrayList<>();
        int i = 0;
        YmlNode item = Mockito.mock(YmlNode.class);
        Object kiwi = Mockito.mock(Object.class);
        itemsList.add(items);
        itemList.add(item);

        when(items.findValues("item")).thenReturn(itemList);
        when(item.findValue("order")).thenReturn(kiwi);
        forEachIf.addOrderIfAbsent(itemsList);

        verify(item, never()).put("order", i);
    }
}
