package org.codetab.uknit.itest.flow;

public class SwitchCaseTest {
    @InjectMocks
    private SwitchCase switchCase;

    @BeforeEach
    public void setUp() throws Exception {
        MockitoAnnotations.openMocks(this);
    }

    @Test
    public void testGetMonth() {
        int month = 1;
        String monthString = "January";

        String actual = switchCase.getMonth(month);

        assertEquals(monthString, actual);
    }
}
