package org.codetab.uknit.itest.linked;

import org.codetab.uknit.itest.linked.Model.Dog;
import org.codetab.uknit.itest.linked.Model.Pet;
import org.codetab.uknit.itest.linked.Model.Pitbull;

public class CastHierarchyInternalTest {
    @InjectMocks
    private CastHierarchyInternal castHierarchyInternal;

    @BeforeEach
    public void setUp() throws Exception {
        MockitoAnnotations.openMocks(this);
    }

    @Test
    public void testHigerLast() {
        Dog obj = Mockito.mock(Dog.class);
        Pet pet2 = obj;
        Pet pet = pet2;
        String apple = "Foo";
        Dog dog2 = obj;
        Dog dog = dog2;
        String grape = "Bar";

        when(pet.sex()).thenReturn(apple);
        when(dog.breed()).thenReturn(grape);

        String actual = castHierarchyInternal.higerLast(obj);

        assertEquals(grape, actual);
    }

    @Test
    public void testLowerLast() {
        Dog obj = Mockito.mock(Dog.class);
        Dog dog2 = obj;
        Dog dog = dog2;
        String apple = "Foo";
        Pet pet2 = obj;
        Pet pet = pet2;
        String grape = "Bar";

        when(dog.breed()).thenReturn(apple);
        when(pet.sex()).thenReturn(grape);

        String actual = castHierarchyInternal.lowerLast(obj);

        assertEquals(grape, actual);
    }

    @Test
    public void testHigherMiddle() {
        Pitbull obj = Mockito.mock(Pitbull.class);
        Dog dog2 = obj;
        Dog dog = dog2;
        String apple = "Foo";
        Pitbull pitbull2 = obj;
        Pitbull pitbull = pitbull2;
        String grape = "Bar";
        Pet pet2 = obj;
        Pet pet = pet2;
        String orange = "Baz";

        when(dog.breed()).thenReturn(apple);
        when(pitbull.name()).thenReturn(grape);
        when(pet.sex()).thenReturn(orange);

        String actual = castHierarchyInternal.higherMiddle(obj);

        assertEquals(orange, actual);
    }

    @Test
    public void testHigherLast() {
        Pitbull obj = Mockito.mock(Pitbull.class);
        Dog dog2 = obj;
        Dog dog = dog2;
        String apple = "Foo";
        Pet pet2 = obj;
        Pet pet = pet2;
        String grape = "Bar";
        Pitbull pitbull2 = obj;
        Pitbull pitbull = pitbull2;
        String orange = "Baz";

        when(dog.breed()).thenReturn(apple);
        when(pet.sex()).thenReturn(grape);
        when(pitbull.name()).thenReturn(orange);

        String actual = castHierarchyInternal.higherLast(obj);

        assertEquals(orange, actual);
    }

    @Test
    public void testHigherFirst() {
        Pitbull obj = Mockito.mock(Pitbull.class);
        Pitbull pitbull2 = obj;
        Pitbull pitbull = pitbull2;
        String apple = "Foo";
        Pet pet2 = obj;
        Pet pet = pet2;
        String grape = "Bar";
        Dog dog2 = obj;
        Dog dog = dog2;
        String orange = "Baz";

        when(pitbull.name()).thenReturn(apple);
        when(pet.sex()).thenReturn(grape);
        when(dog.breed()).thenReturn(orange);

        String actual = castHierarchyInternal.higherFirst(obj);

        assertEquals(orange, actual);
    }

    @Test
    public void testHigerLastMix() {
        Dog obj = Mockito.mock(Dog.class);
        Pet pet = obj;
        String apple = "Foo";
        Dog dog2 = obj;
        Dog dog = dog2;
        String grape = "Bar";

        when(pet.sex()).thenReturn(apple);
        when(dog.breed()).thenReturn(grape);

        String actual = castHierarchyInternal.higerLastMix(obj);

        assertEquals(grape, actual);
    }

    @Test
    public void testLowerLastMix() {
        Dog obj = Mockito.mock(Dog.class);
        Dog dog = obj;
        String apple = "Foo";
        Pet pet2 = obj;
        Pet pet = pet2;
        String grape = "Bar";

        when(dog.breed()).thenReturn(apple);
        when(pet.sex()).thenReturn(grape);

        String actual = castHierarchyInternal.lowerLastMix(obj);

        assertEquals(grape, actual);
    }

    @Test
    public void testHigherMiddleMix() {
        Pitbull obj = Mockito.mock(Pitbull.class);
        Dog dog2 = obj;
        Dog dog = dog2;
        String apple = "Foo";
        Pitbull pitbull = obj;
        String grape = "Bar";
        Pet pet2 = obj;
        Pet pet = pet2;
        String orange = "Baz";

        when(dog.breed()).thenReturn(apple);
        when(pitbull.name()).thenReturn(grape);
        when(pet.sex()).thenReturn(orange);

        String actual = castHierarchyInternal.higherMiddleMix(obj);

        assertEquals(orange, actual);
    }

    @Test
    public void testHigherLastMix() {
        Pitbull obj = Mockito.mock(Pitbull.class);
        Dog dog = obj;
        String apple = "Foo";
        Pet pet = obj;
        String grape = "Bar";
        Pitbull pitbull2 = obj;
        Pitbull pitbull = pitbull2;
        String orange = "Baz";

        when(dog.breed()).thenReturn(apple);
        when(pet.sex()).thenReturn(grape);
        when(pitbull.name()).thenReturn(orange);

        String actual = castHierarchyInternal.higherLastMix(obj);

        assertEquals(orange, actual);
    }

    @Test
    public void testHigherFirstMix() {
        Pitbull obj = Mockito.mock(Pitbull.class);
        Pitbull pitbull = obj;
        String apple = "Foo";
        Pet pet = obj;
        String grape = "Bar";
        Dog dog2 = obj;
        Dog dog = dog2;
        String orange = "Baz";

        when(pitbull.name()).thenReturn(apple);
        when(pet.sex()).thenReturn(grape);
        when(dog.breed()).thenReturn(orange);

        String actual = castHierarchyInternal.higherFirstMix(obj);

        assertEquals(orange, actual);
    }
}
