package org.codetab.uknit.itest.flow.nosplit;

public class ContinueFlowTest {
    @InjectMocks
    private ContinueFlow continueFlow;

    @BeforeEach
    public void setUp() throws Exception {
        MockitoAnnotations.openMocks(this);
    }

    @Test
    public void testPlainContinue() {
        int numPs = 0;

        int actual = continueFlow.plainContinue();

        assertEquals(numPs, actual);
    }

    @Test
    public void testLabeledContinue() {

        boolean actual = continueFlow.labeledContinue();

        assertTrue(actual);
    }
}
