package org.codetab.uknit.itest.flow.nosplit;

import java.util.Map;
import org.codetab.uknit.itest.model.Pet;

public class InferredForEachTest {
    @InjectMocks
    private InferredForEach inferredForEach;

    @BeforeEach
    public void setUp() throws Exception {
        MockitoAnnotations.openMocks(this);
    }

    @Test
    public void testProcess() {
        Map<String, Pet> pets = new HashMap<>();
        String key = "Foo";
        inferredForEach.process(pets);
        fail("unable to assert, STEPIN");
    }
}
