package org.codetab.uknit.itest.interfaces;

import org.codetab.uknit.itest.model.Person;

public class CheckPersonTest {
    @InjectMocks
    private CheckPerson checkPerson;

    @BeforeEach
    public void setUp() throws Exception {
        MockitoAnnotations.openMocks(this);
    }

    @Test
    public void testCheck() {
        Person p = Mockito.mock(Person.class);
        Sex sex = Person.Sex.FEMALE;
        int grape = 1;
        int mango = 1;

        when(p.getGender()).thenReturn(sex);
        when(p.getAge()).thenReturn(grape).thenReturn(mango);

        boolean actual = checkPerson.check(p);

        assertTrue(actual);
    }
}
