package org.codetab.uknit.itest.getset.detect;

import java.util.Date;

public class PseudoGetterTest {
    @InjectMocks
    private PseudoGetter pseudoGetter;

    @Mock
    private Payload payload;

    @BeforeEach
    public void setUp() throws Exception {
        MockitoAnnotations.openMocks(this);
    }

    @Test
    public void testGetDate() {
        Date date = Mockito.mock(Date.class);
        pseudoGetter.setDate(date);

        when(payload.getDate()).thenReturn(date);

        Date actual = pseudoGetter.getDate();

        assertSame(date, actual);
    }
}
