package org.codetab.uknit.itest.getset.detect;

import java.util.Date;

public class SimpleGetterSetterTest {
    @InjectMocks
    private SimpleGetterSetter simpleGetterSetter;

    @Mock
    private Date birthday;

    @BeforeEach
    public void setUp() throws Exception {
        MockitoAnnotations.openMocks(this);
    }

    @Test
    public void testGetName() {
        String name = "Foo";
        simpleGetterSetter.setName(name);

        String actual = simpleGetterSetter.getName();

        assertEquals(name, actual);
    }

    @Test
    public void testSetName() {
        String name = "Foo";
        simpleGetterSetter.setName(name);

        Object actual = simpleGetterSetter.getName();

        assertSame(name, actual);
    }

    @Test
    public void testGetBirthday() {

        Date actual = simpleGetterSetter.getBirthday();

        assertSame(birthday, actual);
    }

    @Test
    public void testSetBirthday() {
        Date birthday = Mockito.mock(Date.class);
        simpleGetterSetter.setBirthday(birthday);

        Object actual = simpleGetterSetter.getBirthday();

        assertSame(birthday, actual);
    }
}
