package org.codetab.uknit.itest.clz;

import java.time.LocalDate;
import java.time.LocalDateTime;
import java.util.ArrayList;
import java.util.List;
import org.apache.logging.log4j.LogManager;
import org.apache.logging.log4j.Logger;

public class FieldTest {
    @InjectMocks
    private Field field;

    @Mock
    private LocalDate date;
    @Mock
    private LocalDate dateA;
    @Mock
    private LocalDate dateB;
    @Mock
    private LocalDateTime dateTimeA;
    @Mock
    private LocalDateTime dateTimeB;

    @BeforeEach
    public void setUp() throws Exception {
        MockitoAnnotations.openMocks(this);
    }

    @Test
    public void testGetDateStr() {
        LocalDate dateP = Mockito.mock(LocalDate.class);
        String apple = "Foo";

        when(dateP.toString()).thenReturn(apple);

        String actual = field.getDateStr(dateP);

        assertEquals(apple, actual);
    }
}
