package org.codetab.uknit.itest.clz;

import java.util.Date;

public class MultiClzTest {
    @InjectMocks
    private MultiClz multiClz;

    @Mock
    private Date fooBirthDay;

    @BeforeEach
    public void setUp() throws Exception {
        MockitoAnnotations.openMocks(this);
    }

    @Test
    public void testGetFooBirthDay() {

        Date actual = multiClz.getFooBirthDay();

        assertSame(fooBirthDay, actual);
    }
}
