package org.codetab.uknit.itest.clz;

import java.util.Date;

public class TwinsBarTest {
    @InjectMocks
    private TwinsBar twinsBar;

    @Mock
    private Date barBirthDay;

    @BeforeEach
    public void setUp() throws Exception {
        MockitoAnnotations.openMocks(this);
    }

    @Test
    public void testGetBarBirthDay() {

        Date actual = twinsBar.getBarBirthDay();

        assertSame(barBirthDay, actual);
    }
}
