package org.codetab.uknit.jtest.expstmt;

import java.util.concurrent.atomic.AtomicInteger;

public class ExpStmtTest {
    @InjectMocks
    private ExpStmt expStmt;

    @BeforeEach
    public void setUp() throws Exception {
        MockitoAnnotations.openMocks(this);
    }

    @Test
    public void testFoo() {
        AtomicInteger counter = Mockito.mock(AtomicInteger.class);
        expStmt.foo(counter);

        verify(counter).decrementAndGet();
    }
}
